import { PermissionKey } from '@/lib/validation/permission';

export interface RolePreset {
  key: string;
  name: string;
  description: string;
  permissions: PermissionKey[];
}

export const ROLE_PRESETS: RolePreset[] = [
  {
    key: 'cashier',
    name: 'Cashier',
    description: 'Front-of-house billing, order viewing, payment recording, and receipt printing.',
    permissions: [
      'orders.view',
      'orders.history.view',
      'cashier.access',
      'payments.view',
      'payments.record',
      'receipts.print',
      'menu.view',
      'tables.view',
      'reports.view',
    ],
  },
  {
    key: 'kitchen_staff',
    name: 'Kitchen Staff',
    description: 'Back-of-house ticket display queue access, kitchen status updates, stock viewing, and waste recording.',
    permissions: [
      'orders.view',
      'kitchen.access',
      'kitchen.orders.view',
      'kitchen.update',
      'menu.view',
      'inventory.view',
      'inventory.counts.manage',
      'inventory.waste.record',
      'recipes.view',
      'inventory.production.manage',
    ],
  },
  {
    key: 'waiter',
    name: 'Waiter',
    description: 'Guest table service requests, table order creation, and menu/table visibility.',
    permissions: [
      'orders.view',
      'waiter.access',
      'waiter.requests.view',
      'waiter.requests.manage',
      'waiter.orders.create',
      'menu.view',
      'tables.view',
      'tables.status.update',
    ],
  },
  {
    key: 'branch_manager',
    name: 'Branch Manager',
    description: 'Operational manager with full branch-scoped management and inventory permissions.',
    permissions: [
      'orders.view',
      'orders.create',
      'orders.update_status',
      'orders.cancel',
      'orders.history.view',
      'waiter.access',
      'waiter.requests.view',
      'waiter.requests.manage',
      'waiter.orders.create',
      'kitchen.access',
      'kitchen.orders.view',
      'kitchen.update',
      'cashier.access',
      'payments.view',
      'payments.record',
      'receipts.print',
      'menu.view',
      'menu.items.create',
      'menu.items.edit',
      'menu.price.update',
      'menu.availability.update',
      'menu.items.delete',
      'menu.categories.manage',
      'menu.modifiers.manage',
      'menu.manage',
      'tables.view',
      'tables.status.update',
      'tables.create',
      'tables.edit',
      'tables.delete',
      'tables.manage',
      'areas.view',
      'areas.manage',
      'qr.view',
      'qr.generate',
      'qr.manage',
      'staff.view',
      'staff.invite',
      'staff.edit',
      'staff.suspend',
      'staff.role.assign',
      'staff.area.assign',
      'staff.manage',
      'reports.view',
      'reports.financial.view',
      'reports.export',
      'inventory.view',
      'inventory.items.manage',
      'inventory.costs.view',
      'inventory.adjust',
      'inventory.counts.manage',
      'inventory.counts.approve',
      'inventory.waste.record',
      'inventory.transfers.manage',
      'inventory.transfers.receive',
      'inventory.locations.manage',
      'inventory.reports.view',
      'recipes.view',
      'recipes.manage',
      'recipes.costs.view',
      'purchasing.view',
      'purchasing.create',
      'purchasing.approve',
      'purchasing.receive',
      'suppliers.view',
      'suppliers.manage',
      'inventory.cogs.view',
      'inventory.menu_profitability.view',
      'inventory.settings.manage',
      'inventory.production.manage',
      'reservations.view',
      'reservations.create',
      'reservations.manage',
      'reservations.cancel',
      'reservations.assign_tables',
      'reservations.waitlist_manage',
    ],
  },
  {
    key: 'supervisor',
    name: 'Supervisor',
    description: 'Floor supervisor with menu stock toggles, table layout, and operational sales reporting.',
    permissions: [
      'orders.view',
      'orders.update_status',
      'orders.history.view',
      'menu.view',
      'menu.availability.update',
      'tables.view',
      'tables.status.update',
      'reports.view',
    ],
  },
];

export function getPermissionsForPreset(presetKey: string): PermissionKey[] {
  const preset = ROLE_PRESETS.find((p) => p.key === presetKey);
  return preset ? [...preset.permissions] : [];
}
