/**
 * WSNexa Offline Resilience & Synchronization Engine Types
 * Phase 38 Mobile Foundation
 */

export type MutationStatus = 'pending' | 'syncing' | 'synced' | 'failed' | 'conflict';

export type EntityType = 
  | 'order'
  | 'order_draft'
  | 'table_status'
  | 'table_note'
  | 'kitchen_ticket'
  | 'inventory_count'
  | 'waiter_request';

export type MutationClassification = 
  | 'READ_ONLY_CACHEABLE'
  | 'ONLINE_ONLY'
  | 'OFFLINE_QUEUEABLE'
  | 'FORBIDDEN_OFFLINE';

export interface QueuedMutation<TPayload = Record<string, unknown>> {
  /** Deterministic UUIDv4 idempotency key generated by client */
  operation_id: string;
  /** Type of entity being mutated */
  entity_type: EntityType;
  /** Identifier of the target entity (or client-generated draft ID) */
  entity_id: string;
  /** Semantic action name (e.g. 'submit_order', 'update_table_status', 'record_count') */
  action: string;
  /** Complete operation payload */
  payload: TPayload;
  /** Current synchronization status */
  status: MutationStatus;
  /** ISO timestamp when mutation was queued */
  created_at: string;
  /** Milliseconds timestamp when queued (for sorting) */
  client_timestamp: number;
  /** Number of synchronization attempts executed */
  attempt_count: number;
  /** Maximum allowable attempts before entering permanent failed state */
  max_attempts: number;
  /** ISO timestamp of most recent attempt */
  last_attempt_at?: string;
  /** Human-readable error message from server or network */
  last_error?: string;
  /** HTTP status code returned by server on failure */
  last_http_status?: number;
  /** Authoritative server response upon success or conflict */
  server_response?: unknown;
  /** User who initiated the mutation (for multi-user isolation) */
  user_id: string;
  /** Active branch context (for multi-tenant isolation) */
  branch_id: string;
  /** Active business/tenant context */
  business_id: string;
}

export interface NetworkState {
  /** Whether the device currently has active network connectivity */
  connected: boolean;
  /** Connection type: 'wifi', 'cellular', 'ethernet', 'none', 'unknown' */
  connection_type: 'wifi' | 'cellular' | 'ethernet' | 'none' | 'unknown';
  /** Last time network transition occurred */
  last_changed_at: string;
}

export interface SyncEngineStats {
  pending_count: number;
  syncing_count: number;
  synced_count: number;
  failed_count: number;
  conflict_count: number;
  last_synced_at: string | null;
  is_syncing: boolean;
}

export interface OfflineCacheRecord<TData = unknown> {
  key: string;
  data: TData;
  cached_at: string;
  expires_at?: string;
  branch_id: string;
  business_id: string;
}
