import { HelpCategory } from './types';

export const HELP_CATEGORIES: HelpCategory[] = [
  {
    id: 'getting-started',
    title: 'Getting Started',
    description: 'Essential guides to launch your restaurant, cafe, or bar on WSNexa.',
    icon: '🚀',
    order: 1,
  },
  {
    id: 'business-branches',
    title: 'Business & Branches',
    description: 'Configure corporate profiles, multi-branch outlets, and operating modes.',
    icon: '🏢',
    order: 2,
  },
  {
    id: 'menu-management',
    title: 'Menu Management',
    description: 'Categories, food & drink items, modifiers, pricing, and sold-out availability.',
    icon: '🍽️',
    order: 3,
  },
  {
    id: 'service-areas-tables-qr',
    title: 'Service Areas, Tables & QR',
    description: 'Floor plans, table access PINs, QR code generation, and session security.',
    icon: '🪑',
    order: 4,
  },
  {
    id: 'orders',
    title: 'Orders & Lifecycle',
    description: 'Tracking orders from customer submission to kitchen prep and completion.',
    icon: '🧾',
    order: 5,
  },
  {
    id: 'staff-roles-permissions',
    title: 'Staff, Roles & Permissions',
    description: 'Inviting staff, role assignments, custom permission overrides, and area routing.',
    icon: '👥',
    order: 6,
  },
  {
    id: 'waiter-operations',
    title: 'Waiter Operations',
    description: 'Taking table orders, guest assistance calls, and approving pending guest orders.',
    icon: '🤵',
    order: 7,
  },
  {
    id: 'kitchen-operations',
    title: 'Kitchen Operations',
    description: 'Live order queue tickets, item modifiers, preparation notes, and status alerts.',
    icon: '🍳',
    order: 8,
  },
  {
    id: 'cashier-payments',
    title: 'Cashier & Payments',
    description: 'POS order settlement, cash & card recording, and printable customer receipts.',
    icon: '💳',
    order: 9,
  },
  {
    id: 'order-security',
    title: 'Order Security',
    description: 'Anti-tamper protection, table PIN verification, and geolocation enforcement.',
    icon: '🛡️',
    order: 10,
  },
  {
    id: 'venue-profile-discovery',
    title: 'Venue Profile & Discovery',
    description: 'Public showcase, logo & cover media, Google Maps location, and reviews.',
    icon: '📍',
    order: 11,
  },
  {
    id: 'account-settings',
    title: 'Account & Settings',
    description: 'Profile preferences, password security, and multi-tenant business switching.',
    icon: '⚙️',
    order: 12,
  },
  {
    id: 'troubleshooting',
    title: 'Troubleshooting Center',
    description: 'Practical solutions to common operational, network, and ordering issues.',
    icon: '🔧',
    order: 13,
  },
  {
    id: 'coming-soon',
    title: 'Coming Soon & Roadmap',
    description: 'Upcoming capabilities and platform enhancements planned for future updates.',
    icon: '✨',
    order: 14,
  },
];
