import { HelpCategory } from './types';

export const HELP_CATEGORIES: HelpCategory[] = [
  {
    id: 'getting-started',
    title: 'Getting Started',
    titleSiEn: 'Getting Started (ආරම්භ කිරීම)',
    description: 'Essential guides to launch your restaurant, cafe, or bar on WSNexa.',
    descriptionSiEn: 'ඔබගේ restaurant, cafe හෝ bar එක WSNexa මඟින් පහසුවෙන් ආරම්භ කිරීමට මඟපෙන්වීම්.',
    icon: '🚀',
    order: 1,
  },
  {
    id: 'business-branches',
    title: 'Business & Branches',
    titleSiEn: 'Business & Branches (ව්‍යාපාරය සහ ශාඛා)',
    description: 'Configure corporate profiles, multi-branch outlets, and operating modes.',
    descriptionSiEn: 'Business Profile, Branch Outlets, සහ Operating Hours සකස් කරගන්නා ආකාරය.',
    icon: '🏢',
    order: 2,
  },
  {
    id: 'service-areas-tables-qr',
    title: 'Service Areas, Tables & QR',
    titleSiEn: 'Service Areas, Tables & QR Codes',
    description: 'Floor plans, table access PINs, QR code generation, and session security.',
    descriptionSiEn: 'Service Areas නිර්මාණය, Tables එකතු කිරීම සහ Table QR Codes generate කිරීම.',
    icon: '🪑',
    order: 3,
  },
  {
    id: 'menu-management',
    title: 'Menu Management',
    titleSiEn: 'Menu Management (මෙනුව සැකසීම)',
    description: 'Categories, food & drink items, modifiers, pricing, and sold-out availability.',
    descriptionSiEn: 'Menu Categories, Menu Items, Modifiers සහ Item Availability කළමනාකරණය.',
    icon: '🍽️',
    order: 4,
  },
  {
    id: 'orders',
    title: 'Orders & Lifecycle',
    titleSiEn: 'Orders & Lifecycle (ඇණවුම් ක්‍රියාවලිය)',
    description: 'Tracking orders from customer submission to kitchen prep and completion.',
    descriptionSiEn: 'Customer order එකක් submit කළ මොහොතේ සිට Kitchen සහ Cashier දක්වා ගලායන ආකාරය.',
    icon: '🧾',
    order: 5,
  },
  {
    id: 'order-security',
    title: 'Order Security & Payments',
    titleSiEn: 'Order Security & Payments',
    description: 'Anti-tamper protection, table PIN verification, and payment gateway configuration.',
    descriptionSiEn: 'Order Security සැකසීම, Waiter Approval, සහ Payment Methods සක්‍රිය කිරීම.',
    icon: '🛡️',
    order: 6,
  },
  {
    id: 'staff-roles-permissions',
    title: 'Staff, Roles & Permissions',
    titleSiEn: 'Staff, Roles & Permissions',
    description: 'Inviting staff, role assignments, custom permission overrides, and area routing.',
    descriptionSiEn: 'Staff සාමාජිකයින් invite කිරීම, Built-in Roles සහ Custom Permissions ලබාදීම.',
    icon: '👥',
    order: 7,
  },
  {
    id: 'waiter-operations',
    title: 'Waiter Operations',
    titleSiEn: 'Waiter Operations (වේටර් මෙහෙයුම්)',
    description: 'Taking table orders, guest assistance calls, and approving pending guest orders.',
    descriptionSiEn: 'Waiter Terminal එකෙන් table orders ගැනීම සහ Guest Assistance calls වලට ප්‍රතිචාර දැක්වීම.',
    icon: '🤵',
    order: 8,
  },
  {
    id: 'kitchen-operations',
    title: 'Kitchen Operations',
    titleSiEn: 'Kitchen Operations (මුළුතැන්ගෙයි මෙහෙයුම්)',
    description: 'Live order queue tickets, item modifiers, preparation notes, and status alerts.',
    descriptionSiEn: 'Kitchen Queue / KDS මඟින් live tickets බැලීම සහ Order Status update කිරීම.',
    icon: '🍳',
    order: 9,
  },
  {
    id: 'cashier-payments',
    title: 'Cashier & Settlement',
    titleSiEn: 'Cashier & POS Settlement',
    description: 'POS order settlement, cash & card recording, and printable customer receipts.',
    descriptionSiEn: 'Cashier POS මඟින් orders settle කිරීම, Cash/Card payments සටහන් කිරීම.',
    icon: '💳',
    order: 10,
  },
  {
    id: 'inventory-management',
    title: 'Inventory & Operations',
    titleSiEn: 'Inventory & Operations (තොග කළමනාකරණය)',
    description: 'Track raw ingredients, storage locations, stock counts, waste, and transfers.',
    descriptionSiEn: 'Stock Items, Recipes/BOM, Suppliers, Purchase Orders සහ Stock Counts කළමනාකරණය.',
    icon: '🥦',
    order: 11,
  },
  {
    id: 'venue-profile-discovery',
    title: 'Venue Profile & Customers',
    titleSiEn: 'Venue Profile & Customers',
    description: 'Public showcase, logo & cover media, Google Maps location, and reviews.',
    descriptionSiEn: 'Public Venue Profile, Customer Reviews, සහ Table Reservations මූලික සැකසුම්.',
    icon: '📍',
    order: 12,
  },
  {
    id: 'troubleshooting',
    title: 'Troubleshooting Center',
    titleSiEn: 'Troubleshooting (ගැටළු විසඳීම)',
    description: 'Practical solutions to common operational, network, and ordering issues.',
    descriptionSiEn: 'QR නොපෙනීම, Table PIN වැරදි වීම, Kitchen එකට order නොයෑම වැනි ගැටළු විසඳීම.',
    icon: '🔧',
    order: 13,
  },
  {
    id: 'coming-soon',
    title: 'Coming Soon & Roadmap',
    titleSiEn: 'Coming Soon & Roadmap (ඉදිරි විශේෂාංග)',
    description: 'Upcoming capabilities and platform enhancements planned for future updates.',
    descriptionSiEn: 'ඉදිරි සංස්කරණ සඳහා සැලසුම් කර ඇති නව විශේෂාංග පිළිබඳ තොරතුරු.',
    icon: '✨',
    order: 14,
  },
  {
    id: 'account-settings',
    title: 'Account, Reports & Subscriptions',
    titleSiEn: 'Account, Reports සහ Subscriptions',
    description: 'Profile credentials, sales reports, exports, and SaaS plan upgrades.',
    descriptionSiEn: 'User profile, Sales Reports, Data Export සහ Subscription Plans කළමනාකරණය.',
    icon: '📊',
    order: 15,
  },
];



