import { AnalyticsMetricKey, MetricDefinition } from './analytics-types';

export const METRIC_REGISTRY: Record<AnalyticsMetricKey, MetricDefinition> = {
  // --- SALES METRICS ---
  gross_sales: {
    key: 'gross_sales',
    label: 'Gross Sales',
    description: 'Total revenue from all placed non-cancelled orders including subtotals, taxes, and fees before refunds.',
    category: 'sales',
    unit: 'currency',
    grain: 'order',
    aggregationSemantics: 'sum',
    supportedFilters: ['date_range', 'branch', 'service_area', 'payment_method'],
    sourceDomains: ['orders'],
    isCurrencyBased: true,
    isComparisonMeaningful: true,
    formula: 'SUM(orders.total_cents) WHERE status != "cancelled"',
  },
  net_sales: {
    key: 'net_sales',
    label: 'Net Sales',
    description: 'Actual collected revenue minus recorded refunds and cancellations.',
    category: 'sales',
    unit: 'currency',
    grain: 'payment',
    aggregationSemantics: 'sum',
    supportedFilters: ['date_range', 'branch', 'payment_method'],
    sourceDomains: ['payments'],
    isCurrencyBased: true,
    isComparisonMeaningful: true,
    formula: 'SUM(payments.amount_cents WHERE payment_status = "completed") - SUM(payments.amount_cents WHERE payment_status = "refunded")',
  },
  completed_orders: {
    key: 'completed_orders',
    label: 'Completed Orders',
    description: 'Total count of orders successfully fulfilled and marked completed.',
    category: 'sales',
    unit: 'count',
    grain: 'order',
    aggregationSemantics: 'count',
    supportedFilters: ['date_range', 'branch', 'service_area'],
    sourceDomains: ['orders'],
    isCurrencyBased: false,
    isComparisonMeaningful: true,
    formula: 'COUNT(orders) WHERE status = "completed"',
  },
  placed_orders: {
    key: 'placed_orders',
    label: 'Placed Orders',
    description: 'Total count of all orders submitted regardless of eventual fulfillment status.',
    category: 'sales',
    unit: 'count',
    grain: 'order',
    aggregationSemantics: 'count',
    supportedFilters: ['date_range', 'branch', 'service_area'],
    sourceDomains: ['orders'],
    isCurrencyBased: false,
    isComparisonMeaningful: true,
    formula: 'COUNT(orders)',
  },
  cancelled_orders: {
    key: 'cancelled_orders',
    label: 'Cancelled Orders',
    description: 'Count of orders cancelled after placement.',
    category: 'sales',
    unit: 'count',
    grain: 'order',
    aggregationSemantics: 'count',
    supportedFilters: ['date_range', 'branch', 'service_area'],
    sourceDomains: ['orders'],
    isCurrencyBased: false,
    isComparisonMeaningful: true,
    formula: 'COUNT(orders) WHERE status = "cancelled"',
  },
  rejected_orders: {
    key: 'rejected_orders',
    label: 'Rejected Orders',
    description: 'Count of orders rejected by staff or kitchen prior to preparation.',
    category: 'sales',
    unit: 'count',
    grain: 'order',
    aggregationSemantics: 'count',
    supportedFilters: ['date_range', 'branch', 'service_area'],
    sourceDomains: ['orders'],
    isCurrencyBased: false,
    isComparisonMeaningful: true,
    formula: 'COUNT(orders) WHERE status = "rejected"',
  },
  aov: {
    key: 'aov',
    label: 'Average Order Value',
    description: 'Average revenue generated per non-cancelled order.',
    category: 'sales',
    unit: 'currency',
    grain: 'order',
    aggregationSemantics: 'ratio',
    supportedFilters: ['date_range', 'branch', 'service_area'],
    sourceDomains: ['orders'],
    isCurrencyBased: true,
    isComparisonMeaningful: true,
    formula: 'Gross Sales / (Total Orders - Cancelled Orders)',
  },
  items_sold: {
    key: 'items_sold',
    label: 'Items Sold',
    description: 'Total quantity of menu items sold across non-cancelled orders.',
    category: 'sales',
    unit: 'count',
    grain: 'order_item',
    aggregationSemantics: 'sum',
    supportedFilters: ['date_range', 'branch', 'menu_category'],
    sourceDomains: ['orders', 'menu'],
    isCurrencyBased: false,
    isComparisonMeaningful: true,
    formula: 'SUM(order_items.quantity) WHERE orders.status != "cancelled"',
  },
  avg_items_per_order: {
    key: 'avg_items_per_order',
    label: 'Average Items Per Order',
    description: 'Average number of menu item units per completed order.',
    category: 'sales',
    unit: 'count',
    grain: 'order_item',
    aggregationSemantics: 'ratio',
    supportedFilters: ['date_range', 'branch'],
    sourceDomains: ['orders'],
    isCurrencyBased: false,
    isComparisonMeaningful: true,
    formula: 'Items Sold / Completed Orders',
  },
  revenue_per_order: {
    key: 'revenue_per_order',
    label: 'Revenue per Order',
    description: 'Gross revenue divided by total non-cancelled orders.',
    category: 'sales',
    unit: 'currency',
    grain: 'order',
    aggregationSemantics: 'ratio',
    supportedFilters: ['date_range', 'branch'],
    sourceDomains: ['orders'],
    isCurrencyBased: true,
    isComparisonMeaningful: true,
    formula: 'Gross Sales / Non-Cancelled Orders',
  },
  revenue_per_branch: {
    key: 'revenue_per_branch',
    label: 'Revenue per Branch',
    description: 'Gross sales breakdown by property branch.',
    category: 'sales',
    unit: 'currency',
    grain: 'branch_day',
    aggregationSemantics: 'sum',
    supportedFilters: ['date_range', 'branch'],
    sourceDomains: ['orders'],
    isCurrencyBased: true,
    isComparisonMeaningful: true,
    formula: 'SUM(orders.total_cents) GROUP BY branch_id',
  },
  revenue_per_service_area: {
    key: 'revenue_per_service_area',
    label: 'Revenue per Service Area',
    description: 'Gross sales breakdown by dining service area.',
    category: 'sales',
    unit: 'currency',
    grain: 'order',
    aggregationSemantics: 'sum',
    supportedFilters: ['date_range', 'branch', 'service_area'],
    sourceDomains: ['orders'],
    isCurrencyBased: true,
    isComparisonMeaningful: true,
    formula: 'SUM(orders.total_cents) GROUP BY dining_tables.service_area_id',
  },
  sales_by_payment_method: {
    key: 'sales_by_payment_method',
    label: 'Sales by Payment Method',
    description: 'Total revenue grouped by payment settlement method.',
    category: 'sales',
    unit: 'currency',
    grain: 'payment',
    aggregationSemantics: 'sum',
    supportedFilters: ['date_range', 'branch', 'payment_method'],
    sourceDomains: ['payments'],
    isCurrencyBased: true,
    isComparisonMeaningful: true,
    formula: 'SUM(payments.amount_cents) GROUP BY payment_method',
  },
  sales_by_hour: {
    key: 'sales_by_hour',
    label: 'Sales by Hour',
    description: 'Total revenue aggregated into local 24-hour time buckets.',
    category: 'sales',
    unit: 'currency',
    grain: 'branch_day',
    aggregationSemantics: 'sum',
    supportedFilters: ['date_range', 'branch'],
    sourceDomains: ['orders'],
    isCurrencyBased: true,
    isComparisonMeaningful: true,
    formula: 'SUM(orders.total_cents) GROUP BY EXTRACT(HOUR FROM local_time)',
  },
  sales_by_day: {
    key: 'sales_by_day',
    label: 'Sales by Day',
    description: 'Total revenue aggregated into local calendar days.',
    category: 'sales',
    unit: 'currency',
    grain: 'branch_day',
    aggregationSemantics: 'sum',
    supportedFilters: ['date_range', 'branch'],
    sourceDomains: ['orders'],
    isCurrencyBased: true,
    isComparisonMeaningful: true,
    formula: 'SUM(orders.total_cents) GROUP BY local_date',
  },

  // --- OPERATIONS METRICS ---
  avg_order_acceptance_time: {
    key: 'avg_order_acceptance_time',
    label: 'Average Order Acceptance Time',
    description: 'Average duration in seconds from customer order submission (pending) to staff confirmation.',
    category: 'operations',
    unit: 'duration',
    grain: 'order',
    aggregationSemantics: 'average',
    supportedFilters: ['date_range', 'branch'],
    sourceDomains: ['orders'],
    isCurrencyBased: false,
    isComparisonMeaningful: true,
    formula: 'AVG(confirmed_at - created_at)',
  },
  avg_kitchen_preparation_time: {
    key: 'avg_kitchen_preparation_time',
    label: 'Average Kitchen Preparation Time',
    description: 'Average duration in seconds from kitchen ticket preparation to ready-to-serve state.',
    category: 'operations',
    unit: 'duration',
    grain: 'order',
    aggregationSemantics: 'average',
    supportedFilters: ['date_range', 'branch'],
    sourceDomains: ['orders'],
    isCurrencyBased: false,
    isComparisonMeaningful: true,
    formula: 'AVG(ready_at - preparing_at)',
  },
  avg_fulfillment_time: {
    key: 'avg_fulfillment_time',
    label: 'Average Fulfillment Time',
    description: 'Average total duration in seconds from order submission to final completion.',
    category: 'operations',
    unit: 'duration',
    grain: 'order',
    aggregationSemantics: 'average',
    supportedFilters: ['date_range', 'branch'],
    sourceDomains: ['orders'],
    isCurrencyBased: false,
    isComparisonMeaningful: true,
    formula: 'AVG(completed_at - created_at)',
  },
  pending_order_count: {
    key: 'pending_order_count',
    label: 'Pending Order Count',
    description: 'Current active order queue count awaiting or undergoing fulfillment.',
    category: 'operations',
    unit: 'count',
    grain: 'order',
    aggregationSemantics: 'count',
    supportedFilters: ['branch'],
    sourceDomains: ['orders'],
    isCurrencyBased: false,
    isComparisonMeaningful: false,
    formula: 'COUNT(orders) WHERE status IN ("pending", "confirmed", "preparing", "ready")',
  },
  completion_rate: {
    key: 'completion_rate',
    label: 'Completion Rate',
    description: 'Percentage of placed orders successfully completed.',
    category: 'operations',
    unit: 'percentage',
    grain: 'order',
    aggregationSemantics: 'ratio',
    supportedFilters: ['date_range', 'branch'],
    sourceDomains: ['orders'],
    isCurrencyBased: false,
    isComparisonMeaningful: true,
    formula: '(Completed Orders / Total Placed Orders) * 100',
  },
  cancellation_rate: {
    key: 'cancellation_rate',
    label: 'Cancellation Rate',
    description: 'Percentage of placed orders that were cancelled.',
    category: 'operations',
    unit: 'percentage',
    grain: 'order',
    aggregationSemantics: 'ratio',
    supportedFilters: ['date_range', 'branch'],
    sourceDomains: ['orders'],
    isCurrencyBased: false,
    isComparisonMeaningful: true,
    formula: '(Cancelled Orders / Total Placed Orders) * 100',
  },
  rejection_rate: {
    key: 'rejection_rate',
    label: 'Rejection Rate',
    description: 'Percentage of placed orders rejected before preparation.',
    category: 'operations',
    unit: 'percentage',
    grain: 'order',
    aggregationSemantics: 'ratio',
    supportedFilters: ['date_range', 'branch'],
    sourceDomains: ['orders'],
    isCurrencyBased: false,
    isComparisonMeaningful: true,
    formula: '(Rejected Orders / Total Placed Orders) * 100',
  },

  // --- MENU METRICS ---
  quantity_sold_by_item: {
    key: 'quantity_sold_by_item',
    label: 'Quantity Sold by Item',
    description: 'Units sold breakdown per menu item.',
    category: 'menu',
    unit: 'count',
    grain: 'order_item',
    aggregationSemantics: 'sum',
    supportedFilters: ['date_range', 'branch', 'menu_category'],
    sourceDomains: ['orders', 'menu'],
    isCurrencyBased: false,
    isComparisonMeaningful: true,
    formula: 'SUM(order_items.quantity) GROUP BY menu_item_id',
  },
  revenue_by_item: {
    key: 'revenue_by_item',
    label: 'Revenue by Item',
    description: 'Gross revenue generated per menu item.',
    category: 'menu',
    unit: 'currency',
    grain: 'order_item',
    aggregationSemantics: 'sum',
    supportedFilters: ['date_range', 'branch', 'menu_category'],
    sourceDomains: ['orders', 'menu'],
    isCurrencyBased: true,
    isComparisonMeaningful: true,
    formula: 'SUM(order_items.total_price_cents) GROUP BY menu_item_id',
  },
  item_order_count: {
    key: 'item_order_count',
    label: 'Item Order Count',
    description: 'Number of distinct completed orders containing a specific item.',
    category: 'menu',
    unit: 'count',
    grain: 'order_item',
    aggregationSemantics: 'count',
    supportedFilters: ['date_range', 'branch', 'menu_category'],
    sourceDomains: ['orders', 'menu'],
    isCurrencyBased: false,
    isComparisonMeaningful: true,
    formula: 'COUNT(DISTINCT order_id) GROUP BY menu_item_id',
  },
  item_penetration_rate: {
    key: 'item_penetration_rate',
    label: 'Item Penetration Rate',
    description: 'Percentage of completed orders that include a specific item.',
    category: 'menu',
    unit: 'percentage',
    grain: 'order_item',
    aggregationSemantics: 'ratio',
    supportedFilters: ['date_range', 'branch', 'menu_category'],
    sourceDomains: ['orders', 'menu'],
    isCurrencyBased: false,
    isComparisonMeaningful: true,
    formula: '(Item Order Count / Total Completed Orders) * 100',
  },
  category_sales: {
    key: 'category_sales',
    label: 'Category Sales',
    description: 'Gross revenue aggregated by menu category.',
    category: 'menu',
    unit: 'currency',
    grain: 'order_item',
    aggregationSemantics: 'sum',
    supportedFilters: ['date_range', 'branch', 'menu_category'],
    sourceDomains: ['orders', 'menu'],
    isCurrencyBased: true,
    isComparisonMeaningful: true,
    formula: 'SUM(order_items.total_price_cents) GROUP BY category_id',
  },
  category_quantity: {
    key: 'category_quantity',
    label: 'Category Quantity',
    description: 'Total item units sold aggregated by menu category.',
    category: 'menu',
    unit: 'count',
    grain: 'order_item',
    aggregationSemantics: 'sum',
    supportedFilters: ['date_range', 'branch', 'menu_category'],
    sourceDomains: ['orders', 'menu'],
    isCurrencyBased: false,
    isComparisonMeaningful: true,
    formula: 'SUM(order_items.quantity) GROUP BY category_id',
  },
  estimated_food_cost: {
    key: 'estimated_food_cost',
    label: 'Estimated Food Cost',
    description: 'Calculated recipe ingredient cost for sold items based on BOM costing.',
    category: 'menu',
    unit: 'currency',
    grain: 'order_item',
    aggregationSemantics: 'sum',
    supportedFilters: ['date_range', 'branch', 'menu_category'],
    sourceDomains: ['orders', 'menu', 'inventory'],
    isCurrencyBased: true,
    isComparisonMeaningful: true,
    formula: 'SUM(recipe_cost * quantity) for items with verified recipe cost',
  },
  contribution_margin: {
    key: 'contribution_margin',
    label: 'Contribution Margin',
    description: 'Revenue minus estimated food cost for menu items with valid recipe costs.',
    category: 'menu',
    unit: 'currency',
    grain: 'order_item',
    aggregationSemantics: 'sum',
    supportedFilters: ['date_range', 'branch', 'menu_category'],
    sourceDomains: ['orders', 'menu', 'inventory'],
    isCurrencyBased: true,
    isComparisonMeaningful: true,
    formula: 'Revenue by Item - Estimated Food Cost (Flags PARTIAL quality if cost missing)',
  },

  // --- INVENTORY METRICS ---
  current_stock: {
    key: 'current_stock',
    label: 'Current Stock',
    description: 'Total current inventory balance across storage locations.',
    category: 'inventory',
    unit: 'count',
    grain: 'inventory_movement',
    aggregationSemantics: 'sum',
    supportedFilters: ['branch'],
    sourceDomains: ['inventory'],
    isCurrencyBased: false,
    isComparisonMeaningful: false,
    formula: 'SUM(inventory_balances.quantity)',
  },
  low_stock_item_count: {
    key: 'low_stock_item_count',
    label: 'Low Stock Item Count',
    description: 'Count of inventory items with stock levels at or below min reorder point.',
    category: 'inventory',
    unit: 'count',
    grain: 'inventory_movement',
    aggregationSemantics: 'count',
    supportedFilters: ['branch'],
    sourceDomains: ['inventory'],
    isCurrencyBased: false,
    isComparisonMeaningful: false,
    formula: 'COUNT(items) WHERE stock <= min_reorder_level AND stock > 0',
  },
  out_of_stock_item_count: {
    key: 'out_of_stock_item_count',
    label: 'Out of Stock Item Count',
    description: 'Count of inventory items with stock levels at 0 or less.',
    category: 'inventory',
    unit: 'count',
    grain: 'inventory_movement',
    aggregationSemantics: 'count',
    supportedFilters: ['branch'],
    sourceDomains: ['inventory'],
    isCurrencyBased: false,
    isComparisonMeaningful: false,
    formula: 'COUNT(items) WHERE stock <= 0',
  },
  waste_quantity: {
    key: 'waste_quantity',
    label: 'Waste Quantity',
    description: 'Total recorded ingredient waste volume in base units.',
    category: 'inventory',
    unit: 'count',
    grain: 'inventory_movement',
    aggregationSemantics: 'sum',
    supportedFilters: ['date_range', 'branch'],
    sourceDomains: ['inventory'],
    isCurrencyBased: false,
    isComparisonMeaningful: true,
    formula: 'SUM(inventory_waste_records.quantity)',
  },
  waste_cost_cents: {
    key: 'waste_cost_cents',
    label: 'Waste Cost',
    description: 'Total financial cost of recorded ingredient waste.',
    category: 'inventory',
    unit: 'currency',
    grain: 'inventory_movement',
    aggregationSemantics: 'sum',
    supportedFilters: ['date_range', 'branch'],
    sourceDomains: ['inventory'],
    isCurrencyBased: true,
    isComparisonMeaningful: true,
    formula: 'SUM(waste_records.quantity * item.cost_per_unit)',
  },
  transfer_volume: {
    key: 'transfer_volume',
    label: 'Transfer Volume',
    description: 'Total stock volume transferred between property branches.',
    category: 'inventory',
    unit: 'count',
    grain: 'inventory_movement',
    aggregationSemantics: 'sum',
    supportedFilters: ['date_range', 'branch'],
    sourceDomains: ['inventory'],
    isCurrencyBased: false,
    isComparisonMeaningful: true,
    formula: 'SUM(inventory_stock_transfers.quantity) WHERE status = "received"',
  },

  // --- REPUTATION / REVIEW METRICS ---
  avg_rating: {
    key: 'avg_rating',
    label: 'Average Rating',
    description: 'Average customer star rating score (1.0 to 5.0).',
    category: 'reputation',
    unit: 'rating',
    grain: 'review',
    aggregationSemantics: 'average',
    supportedFilters: ['date_range', 'branch'],
    sourceDomains: ['reviews'],
    isCurrencyBased: false,
    isComparisonMeaningful: true,
    formula: 'AVG(venue_reviews.rating)',
  },
  review_count: {
    key: 'review_count',
    label: 'Review Count',
    description: 'Total number of customer reviews received.',
    category: 'reputation',
    unit: 'count',
    grain: 'review',
    aggregationSemantics: 'count',
    supportedFilters: ['date_range', 'branch'],
    sourceDomains: ['reviews'],
    isCurrencyBased: false,
    isComparisonMeaningful: true,
    formula: 'COUNT(venue_reviews)',
  },
  rating_distribution: {
    key: 'rating_distribution',
    label: 'Rating Distribution',
    description: 'Breakdown of review counts across 1 to 5 star ratings.',
    category: 'reputation',
    unit: 'count',
    grain: 'review',
    aggregationSemantics: 'count',
    supportedFilters: ['date_range', 'branch'],
    sourceDomains: ['reviews'],
    isCurrencyBased: false,
    isComparisonMeaningful: false,
    formula: 'COUNT(venue_reviews) GROUP BY rating',
  },
  response_rate: {
    key: 'response_rate',
    label: 'Response Rate',
    description: 'Percentage of reviews that have received a staff response.',
    category: 'reputation',
    unit: 'percentage',
    grain: 'review',
    aggregationSemantics: 'ratio',
    supportedFilters: ['date_range', 'branch'],
    sourceDomains: ['reviews'],
    isCurrencyBased: false,
    isComparisonMeaningful: true,
    formula: '(Responded Reviews / Total Reviews) * 100',
  },
  unresponded_review_count: {
    key: 'unresponded_review_count',
    label: 'Unresponded Review Count',
    description: 'Count of customer reviews awaiting staff response.',
    category: 'reputation',
    unit: 'count',
    grain: 'review',
    aggregationSemantics: 'count',
    supportedFilters: ['date_range', 'branch'],
    sourceDomains: ['reviews'],
    isCurrencyBased: false,
    isComparisonMeaningful: false,
    formula: 'COUNT(venue_reviews) WHERE owner_response IS NULL',
  },
};

export function getMetricDefinition(key: AnalyticsMetricKey): MetricDefinition {
  const def = METRIC_REGISTRY[key];
  if (!def) {
    throw new Error(`Metric key "${key}" is not registered in METRIC_REGISTRY.`);
  }
  return def;
}

export function getMetricsByCategory(category: string): MetricDefinition[] {
  return Object.values(METRIC_REGISTRY).filter((m) => m.category === category);
}

export function listAllMetrics(): MetricDefinition[] {
  return Object.values(METRIC_REGISTRY);
}
