/**
 * Centralized deterministic operational insight threshold configurations and sample-size guards.
 */

export const INSIGHT_THRESHOLDS = {
  // Sales & Revenue Thresholds
  SALES: {
    DECLINE_WARNING_PERCENT: 10,
    DECLINE_CRITICAL_PERCENT: 20,
    GROWTH_SUCCESS_PERCENT: 10,
    AOV_DECLINE_PERCENT: 8,
    AOV_GROWTH_PERCENT: 10,
  },

  // Operational & Speed Thresholds
  OPERATIONS: {
    MIN_ORDER_SAMPLE_SIZE: 10,
    PREP_TIME_INFO_MINUTES: 15,
    PREP_TIME_WARNING_MINUTES: 20,
    PREP_TIME_CRITICAL_MINUTES: 30,
    PREP_TIME_INCREASE_PERCENT: 20,
    FULFILLMENT_TIME_WARNING_MINUTES: 30,
    PENDING_QUEUE_WARNING_COUNT: 15,
    COMPLETION_RATE_WARNING_PERCENT: 90,
    COMPLETION_RATE_CRITICAL_PERCENT: 80,
    CANCELLATION_RATE_WARNING_PERCENT: 5,
    REJECTION_RATE_WARNING_PERCENT: 5,
  },

  // Menu Performance Thresholds
  MENU: {
    MIN_ITEM_ORDER_SAMPLE: 5,
    TOP_ITEM_PENETRATION_PERCENT: 25,
    ITEM_SALES_DECLINE_PERCENT: 20,
  },

  // Inventory Thresholds
  INVENTORY: {
    LOW_STOCK_WARNING_COUNT: 5,
    OUT_OF_STOCK_CRITICAL_COUNT: 1,
    WASTE_INCREASE_WARNING_PERCENT: 15,
  },

  // Reputation & Review Thresholds
  REPUTATION: {
    MIN_REVIEW_SAMPLE_SIZE: 5,
    RATING_LOW_WARNING: 4.0,
    RATING_LOW_CRITICAL: 3.5,
    UNRESPONDED_REVIEWS_WARNING_COUNT: 5,
    RESPONSE_RATE_WARNING_PERCENT: 75,
    RATING_DECLINE_DELTA: 0.3,
  },
} as const;
