import { createClient } from '@supabase/supabase-js';
import * as fs from 'fs';
import * as path from 'path';

// Parse .env.local
const envPath = path.join(process.cwd(), '.env.local');
if (fs.existsSync(envPath)) {
  const envConfig = fs.readFileSync(envPath, 'utf8');
  for (const line of envConfig.split('\n')) {
    const trimmed = line.trim();
    if (trimmed && !trimmed.startsWith('#') && trimmed.includes('=')) {
      const [key, ...values] = trimmed.split('=');
      process.env[key.trim()] = values.join('=').trim();
    }
  }
}

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || '';
const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY || '';

const admin = createClient(supabaseUrl, serviceRoleKey);

// Known test business naming prefixes generated by verification scripts
const TEST_NAME_PATTERNS = [
  'Grand Ocean Resort',
  'No Coord Cafe',
  'Aura Grand Resort',
  'Secret Garden Draft',
  'Alpha Grand Hotel',
  'Beta Bistro',
  'Gamma Draft Cafe',
  'Aura Webi Hotel',
  'Duplicate Aura Webi',
  'Test Business',
  'Verification Business',
  'Demo Business',
];

async function safeCleanupDemoVenues() {
  console.log('================================================================');
  console.log('  WSNexa Phase 23.1 — Safe Fake/Demo Venue Audit & Cleanup Report');
  console.log('================================================================\n');

  // Fetch all venue public profiles
  const { data: profiles, error } = await admin
    .from('venue_public_profiles')
    .select('id, business_id, display_name, slug, city, created_at, businesses(id, name)');

  if (error || !profiles) {
    console.error('Failed to query venue profiles:', error);
    process.exit(1);
  }

  const demoCandidates: Array<{
    venueId: string;
    displayName: string;
    businessId: string;
    businessName: string;
    reason: string;
  }> = [];

  const realProductionVenues: Array<{
    venueId: string;
    displayName: string;
    businessName: string;
  }> = [];

  for (const p of profiles) {
    const bizObj = p.businesses as unknown as { name?: string };
    const bizName = bizObj?.name || '';
    const isTestName = TEST_NAME_PATTERNS.some(
      (pat) => p.display_name.startsWith(pat) || bizName.startsWith(pat) || p.slug.startsWith(pat.toLowerCase().replace(/ /g, '-'))
    );

    if (isTestName) {
      demoCandidates.push({
        venueId: p.id,
        displayName: p.display_name,
        businessId: p.business_id,
        businessName: bizName,
        reason: `Matches automated script test naming pattern ("${p.display_name}")`,
      });
    } else {
      realProductionVenues.push({
        venueId: p.id,
        displayName: p.display_name,
        businessName: bizName,
      });
    }
  }

  console.log(`🔍 AUDIT REPORT: Found ${demoCandidates.length} test/demo candidate records.`);
  console.log(`🛡️ PROTECTED RECORDS: ${realProductionVenues.length} production records verified safe.\n`);

  console.log('--- TEST / DEMO VENUE CANDIDATES FOR CLEANUP ---');
  demoCandidates.forEach((c, idx) => {
    console.log(`${idx + 1}. [${c.venueId}] "${c.displayName}" (Business: "${c.businessName}") -> Reason: ${c.reason}`);
  });

  if (realProductionVenues.length > 0) {
    console.log('\n--- PROTECTED REAL PRODUCTION RECORDS (WILL NOT BE TOUCHED) ---');
    realProductionVenues.forEach((r, idx) => {
      console.log(`${idx + 1}. [${r.venueId}] "${r.displayName}" (Business: "${r.businessName}")`);
    });
  }

  if (demoCandidates.length === 0) {
    console.log('\n✅ No leftover demo venues found. Database is clean!');
    return;
  }

  console.log('\n🧹 Performing transaction-safe removal of verified test records...');

  const testVenueIds = demoCandidates.map((c) => c.venueId);
  const testBizIds = Array.from(new Set(demoCandidates.map((c) => c.businessId)));

  if (testVenueIds.length > 0) {
    await admin.from('customer_favorite_venues').delete().in('venue_profile_id', testVenueIds);
    await admin.from('venue_reviews').delete().in('venue_profile_id', testVenueIds);
    await admin.from('venue_public_profiles').delete().in('id', testVenueIds);
  }

  for (const bizId of testBizIds) {
    await admin.from('branches').delete().eq('business_id', bizId);
    await admin.from('business_memberships').delete().eq('business_id', bizId);
    await admin.from('businesses').delete().eq('id', bizId);
  }

  console.log(`\n✅ Safely removed ${demoCandidates.length} test/demo venue records without affecting real production data!`);
}

safeCleanupDemoVenues().catch(console.error);
