import { HelpArticle } from '../types';

export const CASHIER_PAYMENTS_ARTICLES: HelpArticle[] = [
  {
    slug: 'cashier-pos-overview',
    title: 'Cashier POS Terminal & Bill Settlement Guide',
    titleSiEn: 'Cashier POS Terminal සහ බිල්පත් Settlement භාවිතය',
    description: 'Learn how cashiers view active table orders, record cash or card payments, and view customer receipts.',
    descriptionSiEn: 'Cashiers විසින් මේස වල orders බැලීම, Cash හෝ Card මඟින් බිල්පත් settle කිරීම සහ Receipts බලාගන්නා ආකාරය.',
    category: 'cashier-payments',
    keywords: ['cashier', 'pos', 'settle bill', 'receipt', 'cash payment', 'card payment'],
    popular: true,
    contextRoutes: ['/dashboard/cashier'],
    estimatedReadMinutes: 3,
    steps: [
      {
        number: 1,
        title: 'Open Cashier POS',
        titleSiEn: 'Cashier POS එක open කරන්න',
        instruction: 'Navigate to Cashier in the sidebar or directly access /dashboard/cashier.',
        instructionSiEn: 'Sidebar එකෙන් Cashier තෝරා හෝ /dashboard/cashier වෙත යන්න.',
      },
      {
        number: 2,
        title: 'Select Active Table Order',
        titleSiEn: 'Active Table Order එක තෝරන්න',
        instruction: 'Locate the order card in the Unpaid queue. Review itemized totals, kitchen preparation status, and remaining balance due.',
        instructionSiEn: 'Unpaid queue එකෙන් අදාළ order card එක බලන්න. Items, Kitchen status සහ Balance Due ගණන පරීක්ෂා කරන්න.',
      },
      {
        number: 3,
        title: 'Record Payment & Settle',
        titleSiEn: 'Payment එක සටහන් කර Settle කරන්න',
        instruction: 'Tap "💳 Settle", select payment method ("Cash", "Terminal Card", "External QR", or "Pay Counter"), verify amount, and click "Confirm Payment".',
        instructionSiEn: '"💳 Settle" click කර payment method එක ("Cash", "Terminal Card", "External QR", හෝ "Pay Counter") තෝරා "Confirm Payment" මඟින් බිල settle කරන්න.',
      },
    ],
    relatedArticles: ['settling-table-bills', 'configuring-payment-methods', 'payment-types-cash-card-online'],
    directAction: {
      label: 'Open Cashier POS',
      labelSiEn: 'Cashier POS වෙත යන්න',
      href: '/dashboard/cashier',
    },
  },
  {
    slug: 'settling-table-bills',
    title: 'How to Settle Orders and View Receipts',
    titleSiEn: 'Orders Settle කිරීම සහ Receipts බැලීම',
    description: 'Step-by-step instructions for recording customer payments and viewing printable receipts in Cashier POS.',
    descriptionSiEn: 'Customer payments සටහන් කිරීම සහ Cashier POS මඟින් receipts බලාගන්නා පියවර.',
    category: 'cashier-payments',
    keywords: ['print receipt', 'settle bill', 'receipt', 'payment settlement'],
    contextRoutes: ['/dashboard/cashier'],
    estimatedReadMinutes: 3,
    steps: [
      {
        number: 1,
        title: 'Open Payment Settlement Modal',
        titleSiEn: 'Payment Settlement Modal එක open කරන්න',
        instruction: 'From /dashboard/cashier, tap the "💳 Settle" button on the target order card.',
        instructionSiEn: '/dashboard/cashier හි අදාළ order card එකෙහි ඇති "💳 Settle" button එක click කරන්න.',
      },
      {
        number: 2,
        title: 'Choose Payment Method & Amount',
        titleSiEn: 'Payment Method එක සහ මුදල තෝරන්න',
        instruction: 'Select Cash, Terminal Card, External QR, or Pay Counter. Enter the payment amount or click "Pay Full Balance".',
        instructionSiEn: 'Cash, Terminal Card, External QR හෝ Pay Counter තෝරන්න. මුදල ඇතුළත් කරන්න හෝ "Pay Full Balance" click කරන්න.',
      },
      {
        number: 3,
        title: 'Confirm Payment & View Receipt',
        titleSiEn: 'Payment එක Confirm කර Receipt එක බලන්න',
        instruction: 'Click "Confirm Payment" to complete the settlement. Tap "🖨️ Receipt" on the order card to view the printable receipt slip.',
        instructionSiEn: '"Confirm Payment" click කර settlement එක අවසන් කරන්න. Order card එකෙහි "🖨️ Receipt" click කර printable receipt එක බලන්න.',
      },
    ],
    relatedArticles: ['cashier-pos-overview', 'configuring-payment-methods'],
    directAction: {
      label: 'Open Cashier POS',
      labelSiEn: 'Cashier POS වෙත යන්න',
      href: '/dashboard/cashier',
    },
  },
  {
    slug: 'configuring-payment-methods',
    title: 'How to Configure Branch Payment Methods',
    titleSiEn: 'Branch Payment Methods සකස් කරගන්නේ කෙසේද?',
    description: 'Configure payment options accepted at your branch for customer checkout and cashier recording.',
    descriptionSiEn: 'ඔබගේ ශාඛාව සඳහා පිළිගන්නා payment options සකස් කරගන්නා ආකාරය.',
    category: 'cashier-payments',
    keywords: ['payment methods', 'enable cash', 'card pos', 'payment settings', 'counter payment'],
    contextRoutes: ['/dashboard/settings/payments'],
    estimatedReadMinutes: 3,
    steps: [
      {
        number: 1,
        title: 'Go to Branch Payment Methods',
        titleSiEn: 'Branch Payment Methods වෙත යන්න',
        instruction: 'From the dashboard sidebar, navigate to Settings → Payment Methods (/dashboard/settings/payments).',
        instructionSiEn: 'Dashboard sidebar එකෙන් Settings → Payment Methods (/dashboard/settings/payments) වෙත යන්න.',
      },
      {
        number: 2,
        title: 'Enable Accepted Methods',
        titleSiEn: 'පිළිගන්නා ක්‍රම සක්‍රිය කරන්න',
        instruction: 'Click the ENABLED / DISABLED toggle for Cash, Terminal Card, or External QR to enable accepted payment methods for this branch.',
        instructionSiEn: 'Cash, Terminal Card හෝ External QR සඳහා ඇති ENABLED / DISABLED toggle එක click කර මෙම ශාඛාවට අවශ්‍ය ක්‍රම සක්‍රිය කරන්න.',
      },
      {
        number: 3,
        title: 'Customize Display Title & Instructions',
        titleSiEn: 'Display Title සහ උපදෙස් ඇතුළත් කරන්න',
        instruction: 'Enter custom customer-facing labels and instructions, then click "Save Method Labels".',
        instructionSiEn: 'පාරිභෝගිකයාට පෙන්වන මාතෘකාව සහ උපදෙස් ඇතුළත් කර "Save Method Labels" click කරන්න.',
      },
    ],
    notes: [
      'Your branch must have at least one active payment method enabled to complete the Ordering Security & Payments stage of Business Setup.',
    ],
    notesSiEn: [
      'Business Setup හි Ordering Security & Payments අදියර සම්පූර්ණ වීමට නම් අවම වශයෙන් එක් payment method එකක් හෝ සක්‍රිය කර තිබිය යුතුය.',
    ],
    relatedArticles: ['payment-types-cash-card-online', 'cashier-pos-overview'],
    directAction: {
      label: 'Configure Payments',
      labelSiEn: 'Payments සැකසීම',
      href: '/dashboard/settings/payments',
    },
  },
  {
    slug: 'payment-types-cash-card-online',
    title: 'Understanding Supported Payment Types',
    titleSiEn: 'WSNexa හි සහය දක්වන Payment Types තේරුම් ගැනීම',
    description: 'Learn how Cash, Terminal Card, External QR, and Pay at Counter methods function in WSNexa.',
    descriptionSiEn: 'Cash, Terminal Card, External QR සහ Pay at Counter ක්‍රම WSNexa තුළ ක්‍රියාත්මක වන ආකාරය.',
    category: 'cashier-payments',
    keywords: ['payment types', 'cash vs card', 'external qr', 'pay at counter', 'terminal card'],
    contextRoutes: ['/dashboard/settings/payments'],
    estimatedReadMinutes: 3,
    steps: [
      {
        number: 1,
        title: 'Pay with Cash',
        titleSiEn: 'Pay with Cash (මුදල් ගෙවීම)',
        instruction: 'Customers pay physical cash directly to the cashier or server; the cashier records the cash settlement in WSNexa.',
        instructionSiEn: 'පාරිභෝගිකයා physical cash ගෙවන අතර, Cashier විසින් එය WSNexa හි Cash settlement එකක් ලෙස සටහන් කරයි.',
      },
      {
        number: 2,
        title: 'Terminal Card Payment',
        titleSiEn: 'Terminal Card Payment (Card Machine එකෙන් ගෙවීම)',
        instruction: 'Customers tap or swipe credit/debit cards on your standalone EDC/POS terminal; the cashier enters the terminal reference in WSNexa.',
        instructionSiEn: 'ස්වාධීන EDC/Card POS terminal එකෙන් card payment එක ගෙන, Cashier විසින් අදාළ reference එක WSNexa හි සටහන් කරයි.',
      },
      {
        number: 3,
        title: 'External QR & Pay at Counter',
        titleSiEn: 'External QR සහ Pay at Counter',
        instruction: 'Customers scan a bank or merchant QR code or pay at the front desk counter; cashier records the received payment.',
        instructionSiEn: 'බැංකු හෝ merchant QR code එකක් scan කර හෝ ප්‍රධාන කවුන්ටරයෙන් ගෙවූ විට Cashier විසින් එය සටහන් කරයි.',
      },
    ],
    relatedArticles: ['configuring-payment-methods', 'cashier-pos-overview'],
    directAction: {
      label: 'Open Payment Settings',
      labelSiEn: 'Payment Settings වෙත යන්න',
      href: '/dashboard/settings/payments',
    },
  },
];

