import { HelpArticle } from '../types';

export const GETTING_STARTED_ARTICLES: HelpArticle[] = [
  {
    slug: 'what-is-wsnexa',
    title: 'What is WSNexa? — Smart Hospitality Platform Overview',
    titleSiEn: 'WSNexa යනු කුමක්ද? — Smart Hospitality Platform හැඳින්වීම',
    description: 'An overview of WSNexa and how it connects QR ordering, waiter terminals, kitchen displays, and cashier settlement into one realtime system.',
    descriptionSiEn: 'WSNexa මඟින් QR ordering, Waiter Terminals, Kitchen Queue සහ Cashier POS එකිනෙක සම්බන්ධ වන ආකාරය පිළිබඳ මූලික හැඳින්වීම.',
    category: 'getting-started',
    keywords: ['welcome', 'overview', 'introduction', 'what is wsnexa', 'features', 'hospitality'],
    popular: true,
    gettingStarted: true,
    estimatedReadMinutes: 3,
    steps: [
      {
        number: 1,
        title: 'Understand the Unified Digital Hospitality Architecture',
        titleSiEn: 'WSNexa Realtime පද්ධතිය තේරුම් ගන්න',
        instruction: 'WSNexa unifies your entire restaurant workflow into a single realtime platform. You configure your menu and floor plan once, and WSNexa automatically powers QR customer menus, waiter mobile ordering, kitchen ticket displays, and cashier settlement.',
        instructionSiEn: 'WSNexa මඟින් ඔබගේ සම්පූර්ණ restaurant මෙහෙයුම් එකම realtime platform එකකට ගෙන එයි. ඔබ Menu සහ Dining Tables එක් වරක් configure කළ පසු, Customer QR menus, Waiter ordering, Kitchen tickets සහ Cashier settlement ස්වයංක්‍රීයව ක්‍රියාත්මක වේ.',
        tip: 'Any changes made to menu prices or sold-out items update instantly across all customer and staff screens without reloading.',
        tipSiEn: 'Menu Items හෝ Prices වල කරන වෙනස්කම් reload කිරීමකින් තොරව සියලුම staff සහ customer screens වලට ක්ෂණිකව update වේ.',
      },
      {
        number: 2,
        title: 'Explore the Role-Based Workspaces',
        titleSiEn: 'Role-Based Workspaces භාවිතා කරන්න',
        instruction: 'Each team member accesses a tailored workspace suited to their responsibilities: Business Owners manage venues and settings; Managers oversee branches and staff; Waiters take orders; Kitchen staff view live prep queues; Cashiers record payments.',
        instructionSiEn: 'සෑම team member කෙනෙකුටම ඔවුන්ගේ කාර්යයට අදාළ workspace එකක් හිමිවේ: Business Owners සැකසුම් පාලනය කරයි; Waiters මේස අසලදී orders ගනී; Kitchen team එක live prep queue බලයි; Cashiers බිල්පත් settle කරයි.',
      },
      {
        number: 3,
        title: 'Complete the Guided Business Setup',
        titleSiEn: 'Business Setup එක සම්පූර්ණ කරන්න',
        instruction: 'Go to Settings → Business Setup to complete the 6 essential configuration stages for your branch.',
        instructionSiEn: 'Settings → Business Setup වෙත ගොස් ඔබගේ ශාඛාව සඳහා අත්‍යවශ්‍ය මූලික සැකසුම් අදියර (Core Setup Stages) 6 සම්පූර්ණ කරන්න.',
      },
    ],
    notes: [
      'WSNexa runs in modern mobile and desktop web browsers without requiring hardware terminals or app downloads.',
    ],
    notesSiEn: [
      'WSNexa කිසිදු අමතර app එකක් download කිරීමකින් තොරව ඕනෑම smartphone හෝ computer browser එකකින් ක්‍රියාත්මක කළ හැක.',
    ],
    relatedArticles: ['complete-business-setup', 'core-vs-recommended-setup', 'add-manage-branches'],
    directAction: {
      label: 'Open Dashboard',
      labelSiEn: 'Dashboard එකට යන්න',
      href: '/dashboard',
    },
  },
  {
    slug: 'complete-business-setup',
    title: 'How to Complete Guided Business Setup',
    titleSiEn: 'Guided Business Setup එක සම්පූර්ණ කරගන්නේ කෙසේද?',
    description: 'Step-by-step guidance on completing the 6 essential configuration stages for your branch.',
    descriptionSiEn: 'ඔබගේ ශාඛාව සඳහා අත්‍යවශ්‍ය මූලික සැකසුම් අදියර (Core Setup Stages) 6 සම්පූර්ණ කරගන්නා ආකාරය.',
    category: 'getting-started',
    keywords: ['setup', 'checklist', 'onboarding', 'business setup', 'wizard', 'readiness'],
    popular: true,
    gettingStarted: true,
    estimatedReadMinutes: 4,
    steps: [
      {
        number: 1,
        title: 'Open Business Setup',
        titleSiEn: 'Business Setup එක open කරන්න',
        instruction: 'From the dashboard sidebar, navigate to Settings → Business Setup (/dashboard/setup).',
        instructionSiEn: 'Dashboard sidebar එකෙන් Settings → Business Setup (/dashboard/setup) වෙත යන්න.',
      },
      {
        number: 2,
        title: 'Complete Core Stages in Order',
        titleSiEn: 'Core stages පිළිවෙලට සම්පූර්ණ කරන්න',
        instruction: 'Follow the 6 mandatory stages: 1. Business Basics, 2. Primary Branch, 3. Dining & QR, 4. Menu & Items, 5. Order Security & Payments, 6. Operational Test Order.',
        instructionSiEn: 'අනිවාර්ය core stages 6 අනුපිළිවෙලින් කරන්න: 1. Business Basics, 2. Primary Branch, 3. Dining & QR, 4. Menu & Items, 5. Order Security & Payments, 6. Operational Test Order.',
      },
      {
        number: 3,
        title: 'Place a Successful Test Order',
        titleSiEn: 'Test Order එකක් place කර verify කරන්න',
        instruction: 'Place a test order via QR or Cashier POS and progress it to Kitchen / Cashier to verify your operational workflow.',
        instructionSiEn: 'QR code එක scan කර හෝ Cashier POS මඟින් test order එකක් දමා Kitchen Queue එකට හෝ Cashier එකට එන බව තහවුරු කරගන්න.',
      },
    ],
    notes: [
      'Once Core Setup reaches 6 of 6, the dashboard setup assistant will automatically collapse.',
    ],
    notesSiEn: [
      'Core Setup හි අදියර 6 ම සම්පූර්ණ වූ පසු Dashboard Setup card එක ස්වයංක්‍රීයව ඉවත් වී සාමාන්‍ය මෙහෙයුම් සඳහා ඉඩ ලබාදේ.',
    ],
    relatedArticles: ['core-vs-recommended-setup', 'create-service-areas', 'create-categories'],
    directAction: {
      label: 'Open Business Setup',
      labelSiEn: 'Business Setup වෙත යන්න',
      href: '/dashboard/setup',
    },
  },
  {
    slug: 'core-vs-recommended-setup',
    title: 'Understanding Core vs Recommended vs Optional Setup',
    titleSiEn: 'Core, Recommended සහ Optional Setup අතර වෙනස තේරුම් ගැනීම',
    description: 'Learn why small cafes only need Core Setup, while advanced restaurants can optionally use Team and Inventory features.',
    descriptionSiEn: 'කුඩා cafe එකකට Core Setup පමණක් ප්‍රමාණවත් වන ආකාරය සහ විශාල restaurants සඳහා Team හා Inventory භාවිතා කරන ආකාරය.',
    category: 'getting-started',
    keywords: ['core setup', 'recommended', 'optional', 'cafe setup', 'tiers'],
    gettingStarted: true,
    estimatedReadMinutes: 3,
    steps: [
      {
        number: 1,
        title: 'Core Setup (Required)',
        titleSiEn: 'Core Setup (අනිවාර්ය අදියර)',
        instruction: 'Includes Business Basics, Location, Dining & QR, Menu, Ordering Security & Payments, and Test Order. Core Setup helps verify the essential WSNexa configuration for this branch.',
        instructionSiEn: 'Business Basics, Location, Dining & QR, Menu, Ordering Security & Payments, සහ Test Order මෙයට අයත් වේ. Core Setup මඟින් මෙම ශාඛාවේ මූලික WSNexa සැකසුම් සම්පූර්ණ බව තහවුරු කරයි.',
      },

      {
        number: 2,
        title: 'Recommended Enhancements',
        titleSiEn: 'Recommended Enhancements (නිර්දේශිත අදියර)',
        instruction: 'Includes Staff Invitations and Public Venue Profile. A single-owner cafe can skip extra staff and still operate 100% normally.',
        instructionSiEn: 'Staff Invitations සහ Public Venue Profile මෙයට අයත් වේ. තනිව ක්‍රියාත්මක වන cafe එකකට staff invite නොකර වුවද සාමාන්‍ය පරිදි orders හැසිරවිය හැක.',
      },
      {
        number: 3,
        title: 'Optional Operations & Supply Chain',
        titleSiEn: 'Optional Operations (විකල්ප අදියර)',
        instruction: 'Includes Inventory stock items, recipe bill of materials, and purchase orders. Use this whenever you want food costing and ingredient tracking.',
        instructionSiEn: 'Inventory stock items, Recipe BOM සහ Purchase Orders මෙයට අයත් වේ. අමුද්‍රව්‍ය පාලනයක් අවශ්‍ය වූ විට මෙය භාවිතා කළ හැක.',
      },
    ],
    relatedArticles: ['complete-business-setup', 'what-is-wsnexa'],
    directAction: {
      label: 'View Setup Progress',
      labelSiEn: 'Setup Progress බලන්න',
      href: '/dashboard/setup',
    },
  },
];
