import { HelpArticle } from '../types';

export const inventoryArticles: HelpArticle[] = [
  {
    slug: 'inventory-quick-start',
    title: 'Inventory Quick Start Guide',
    description: 'Get started tracking raw ingredients, opening stock balances, and storage locations in minutes.',
    category: 'inventory-management',
    keywords: ['inventory', 'stock', 'ingredients', 'raw materials', 'quick start', 'onboarding'],
    allowedRoles: ['business_owner', 'branch_manager'],
    requiredPermissions: ['inventory.view'],
    contextRoutes: ['/dashboard/inventory'],
    gettingStarted: true,
    popular: true,
    estimatedReadMinutes: 3,
    steps: [
      {
        number: 1,
        title: 'Open the Inventory Hub',
        instruction: 'Navigate to "Inventory Hub" from the sidebar menu to view your overall stock health, low-stock warnings, and valuation summary.',
      },
      {
        number: 2,
        title: 'Verify Default Storage Location',
        instruction: 'WSNexa automatically generates a default "Main Stock" location for your branch. You can create specialized locations like "Main Kitchen", "Cold Room", or "Bar Store" at any time under Storage Locations.',
      },
      {
        number: 3,
        title: 'Add Your First Ingredients',
        instruction: 'Click "+ Add Ingredient" to register raw food and beverage items with their base units (kg, g, L, ml, pcs) and optional opening quantities.',
      },
      {
        number: 4,
        title: 'Set Low Stock Thresholds',
        instruction: 'Specify a minimum par stock level for each ingredient so WSNexa can proactively alert you before kitchen lines run out.',
      },
    ],
    notes: [
      'Inventory items are defined at the business level so multiple branches share canonical ingredient names, while physical stock quantities remain strictly branch and location-isolated.',
    ],
    relatedArticles: [
      'adding-inventory-items-and-units',
      'understanding-storage-locations',
      'recording-stock-adjustments-and-waste',
    ],
    directAction: {
      label: 'Go to Inventory Hub',
      href: '/dashboard/inventory',
    },
  },
  {
    slug: 'adding-inventory-items-and-units',
    title: 'Adding Inventory Items & Units',
    description: 'How to register raw ingredients, packaging, unit conversions, and opening balances.',
    category: 'inventory-management',
    keywords: ['add item', 'base unit', 'kg', 'litre', 'ingredient', 'cost', 'opening stock'],
    allowedRoles: ['business_owner', 'branch_manager'],
    requiredPermissions: ['inventory.items.manage'],
    contextRoutes: ['/dashboard/inventory/items', '/dashboard/inventory/items/new'],
    estimatedReadMinutes: 3,
    steps: [
      {
        number: 1,
        title: 'Navigate to Stock Items',
        instruction: 'Go to "/dashboard/inventory/items" and click "+ Add Ingredient".',
      },
      {
        number: 2,
        title: 'Enter Item Name & Category',
        instruction: 'Provide the ingredient name (e.g. Chicken Breast, Whole Milk) and assign it to an inventory category.',
      },
      {
        number: 3,
        title: 'Select Base Measurement Unit',
        instruction: 'Choose the standard base unit (kg, g, L, ml, pcs). All stock balances and future recipe consumptions will be normalized to this unit.',
        tip: 'Choose the smallest practical storage unit for recipes, such as kg for meats or L for liquids.',
      },
      {
        number: 4,
        title: 'Enter Unit Cost & Minimum Par Level',
        instruction: 'Input the estimated cost per base unit and the minimum safety stock threshold.',
      },
      {
        number: 5,
        title: 'Enter Initial Opening Stock (Optional)',
        instruction: 'If you already have stock on hand, enter the current physical quantity and choose the storage location.',
      },
    ],
    notes: [
      'Cost per unit is visible only to users with the "View Inventory Costs & Valuation" permission.',
    ],
    relatedArticles: ['inventory-quick-start', 'understanding-stock-levels'],
    directAction: {
      label: 'Add Ingredient',
      href: '/dashboard/inventory/items/new',
    },
  },
  {
    slug: 'understanding-storage-locations',
    title: 'Managing Branch Storage Locations',
    description: 'Organize physical stock across walk-in freezers, dry stores, bar caches, and kitchen lines.',
    category: 'inventory-management',
    keywords: ['storage location', 'cold room', 'kitchen store', 'bar stock', 'freezer'],
    allowedRoles: ['business_owner', 'branch_manager'],
    requiredPermissions: ['inventory.locations.manage'],
    contextRoutes: ['/dashboard/inventory/locations'],
    estimatedReadMinutes: 2,
    steps: [
      {
        number: 1,
        title: 'Go to Storage Locations',
        instruction: 'Navigate to "/dashboard/inventory/locations" to view all configured storage areas in your active branch.',
      },
      {
        number: 2,
        title: 'Click "+ Add Storage Location"',
        instruction: 'Enter a recognizable name (e.g. Cold Room Chiller) and unique location code (e.g. COLD_ROOM).',
      },
      {
        number: 3,
        title: 'Assign Default Location Status',
        instruction: 'Mark a primary location as "Default Main Stock" if you want new item balances and general deliveries to route there by default.',
      },
    ],
    relatedArticles: ['inventory-quick-start', 'managing-stock-transfers'],
    directAction: {
      label: 'Manage Locations',
      href: '/dashboard/inventory/locations',
    },
  },
  {
    slug: 'recording-stock-adjustments-and-waste',
    title: 'Recording Stock Adjustments & Kitchen Waste',
    description: 'How to manually correct balances, record wholesale deliveries, and log kitchen spoilage.',
    category: 'inventory-management',
    keywords: ['stock adjustment', 'waste', 'spoilage', 'damaged', 'staff meal', 'delivery'],
    allowedRoles: ['business_owner', 'branch_manager', 'kitchen_staff'],
    requiredPermissions: ['inventory.adjust', 'inventory.waste.record'],
    contextRoutes: ['/dashboard/inventory/items', '/dashboard/inventory/waste'],
    popular: true,
    estimatedReadMinutes: 3,
    steps: [
      {
        number: 1,
        title: 'Select Item from Stock Items List',
        instruction: 'Find the ingredient on the Stock Items table and click the "Adjust" or "Waste" button.',
      },
      {
        number: 2,
        title: 'Choose Adjustment Type & Reason',
        instruction: 'For adjustments, select "+ Add Stock", "- Remove", or "= Set Count". For waste, select the reason (Spoiled, Expired, Prep Trimming, Overcooked, Dropped).',
      },
      {
        number: 3,
        title: 'Enter Quantity & Unit',
        instruction: 'Type the quantity and select the measurement unit. WSNexa will automatically convert compatible units (e.g. 500 g -> 0.5 kg).',
      },
      {
        number: 4,
        title: 'Commit Mutation',
        instruction: 'Click "Commit Adjustment" or "Record Waste". The stock balance updates atomically and an immutable movement ledger entry is logged.',
      },
    ],
    relatedArticles: ['performing-physical-stock-counts', 'inventory-quick-start'],
    directAction: {
      label: 'View Waste Log',
      href: '/dashboard/inventory/waste',
    },
  },
  {
    slug: 'performing-physical-stock-counts',
    title: 'Performing Physical Stock Counts & Audits',
    description: 'Conduct mobile-friendly physical stock counts, calculate variances, and reconcile balances.',
    category: 'inventory-management',
    keywords: ['stock count', 'physical audit', 'variance', 'reconciliation', 'blind count'],
    allowedRoles: ['business_owner', 'branch_manager', 'kitchen_staff'],
    requiredPermissions: ['inventory.counts.manage'],
    contextRoutes: ['/dashboard/inventory/counts'],
    estimatedReadMinutes: 4,
    steps: [
      {
        number: 1,
        title: 'Start a New Count Audit Sheet',
        instruction: 'Go to "/dashboard/inventory/counts/new", choose the target storage location, enter a title, and select whether to run a Blind Count.',
      },
      {
        number: 2,
        title: 'Use the Mobile-First Counter Interface',
        instruction: 'Walk through your shelves or walk-in cooler on a mobile phone or tablet, entering counted numbers using large numeric inputs.',
      },
      {
        number: 3,
        title: 'Submit Count Sheet',
        instruction: 'Once all items are audited, click "Submit Count" to send the audit sheet for manager review.',
      },
      {
        number: 4,
        title: 'Approve & Reconcile Variances',
        instruction: 'A manager with count approval permission reviews discrepancies and clicks "Approve & Reconcile" to automatically align system balances with the physical count.',
      },
    ],
    relatedArticles: ['recording-stock-adjustments-and-waste', 'understanding-stock-levels'],
    directAction: {
      label: 'Start Stock Count',
      href: '/dashboard/inventory/counts/new',
    },
  },
  {
    slug: 'managing-stock-transfers',
    title: 'Managing Same-Branch & Cross-Branch Stock Transfers',
    description: 'Dispatch stock between storage areas or across authorized sister outlets with receipt verification.',
    category: 'inventory-management',
    keywords: ['stock transfer', 'dispatch', 'receive', 'transit', 'cross branch'],
    allowedRoles: ['business_owner', 'branch_manager'],
    requiredPermissions: ['inventory.transfers.manage', 'inventory.transfers.receive'],
    contextRoutes: ['/dashboard/inventory/transfers'],
    estimatedReadMinutes: 3,
    steps: [
      {
        number: 1,
        title: 'Create a Draft Transfer',
        instruction: 'Go to "/dashboard/inventory/transfers/new", choose source/destination locations, and add the items and quantities to transfer.',
      },
      {
        number: 2,
        title: 'Dispatch Transfer',
        instruction: 'Click "Dispatch". Source stock is deducted immediately and the transfer is marked "In Transit".',
      },
      {
        number: 3,
        title: 'Acknowledge Inbound Receipt',
        instruction: 'When goods arrive at the destination location, authorized staff click "Receive Stock" to confirm quantities and add items to destination balances.',
      },
    ],
    relatedArticles: ['understanding-storage-locations', 'inventory-quick-start'],
    directAction: {
      label: 'View Stock Transfers',
      href: '/dashboard/inventory/transfers',
    },
  },
  {
    slug: 'understanding-stock-levels',
    title: 'Understanding Stock Levels & Health Insights',
    description: 'How WSNexa calculates real-time inventory balances, stock status badges, and health scores.',
    category: 'inventory-management',
    keywords: ['stock levels', 'health score', 'low stock', 'out of stock', 'par level'],
    allowedRoles: ['business_owner', 'branch_manager'],
    requiredPermissions: ['inventory.view'],
    contextRoutes: ['/dashboard/inventory', '/dashboard/inventory/items'],
    estimatedReadMinutes: 2,
    steps: [
      {
        number: 1,
        title: 'Healthy Stock (Green)',
        instruction: 'Current physical balance exceeds the minimum safety threshold.',
      },
      {
        number: 2,
        title: 'Low Stock Alert (Amber)',
        instruction: 'Current balance is at or below the minimum par level configured on the item.',
      },
      {
        number: 3,
        title: 'Out of Stock (Red)',
        instruction: 'Zero balance available across all storage locations in the active branch.',
      },
      {
        number: 4,
        title: 'Inventory Health Score',
        instruction: 'A 0–100 deterministic score reflecting your venue’s inventory stability based on active stockout penalties and par compliance.',
      },
    ],
    relatedArticles: ['inventory-quick-start', 'adding-inventory-items-and-units'],
    directAction: {
      label: 'View Inventory Health',
      href: '/dashboard/inventory',
    },
  },
  {
    slug: 'recipe-quick-start',
    title: 'Recipe & BOM Costing Quick Start',
    description: 'Learn how to link menu items to inventory ingredients, calculate food cost percentages, and automate stock deduction.',
    category: 'inventory-management',
    keywords: ['recipes', 'bom', 'food cost', 'portioning', 'quick start'],
    allowedRoles: ['business_owner', 'branch_manager'],
    requiredPermissions: ['recipes.view'],
    contextRoutes: ['/dashboard/inventory/recipes'],
    gettingStarted: true,
    popular: true,
    estimatedReadMinutes: 3,
    steps: [
      {
        number: 1,
        title: 'Navigate to Recipes & BOM',
        instruction: 'Click "Recipes & BOM" in the Inventory Hub to view configured dish formulas and gross profit margins.',
      },
      {
        number: 2,
        title: 'Create Your First Recipe',
        instruction: 'Click "+ Create Recipe", choose a menu item, and add the required raw ingredients with exact gram/ml/pcs quantities.',
      },
      {
        number: 3,
        title: 'Review Food Cost % & Margins',
        instruction: 'WSNexa automatically computes portion cost and food cost % dynamically using live ingredient purchase costs.',
      },
    ],
    relatedArticles: ['creating-recipes-and-bom', 'understanding-food-cost-and-margins'],
    directAction: { label: 'Go to Recipes', href: '/dashboard/inventory/recipes' },
  },
  {
    slug: 'creating-recipes-and-bom',
    title: 'Creating Recipes & Bill of Materials (BOM)',
    description: 'How to build multi-ingredient recipe formulas, configure trimming yield factors, and prevent recursive sub-recipe loops.',
    category: 'inventory-management',
    keywords: ['recipe builder', 'bom', 'ingredients', 'portion', 'yield'],
    allowedRoles: ['business_owner', 'branch_manager'],
    requiredPermissions: ['recipes.manage'],
    contextRoutes: ['/dashboard/inventory/recipes/new'],
    estimatedReadMinutes: 4,
    steps: [
      {
        number: 1,
        title: 'Define Portion & Yield',
        instruction: 'Specify the recipe yield quantity (e.g. 1 portion or 5 Litres for prep batches).',
      },
      {
        number: 2,
        title: 'Add Ingredients & Yield Factors',
        instruction: 'Select raw ingredients. If items require trimming or cooking loss (e.g. 88% yield), specify the yield factor so usable food cost is calculated accurately.',
      },
    ],
    relatedArticles: ['recipe-quick-start', 'sub-recipes-and-prep-production'],
  },
  {
    slug: 'understanding-food-cost-and-margins',
    title: 'Understanding Food Cost & Margins',
    description: 'How WSNexa calculates recipe costs, gross profit, and benchmarks food cost percentages against hospitality standards.',
    category: 'inventory-management',
    keywords: ['food cost percentage', 'gross profit', 'margin', 'pricing'],
    allowedRoles: ['business_owner', 'branch_manager'],
    requiredPermissions: ['recipes.costs.view'],
    contextRoutes: ['/dashboard/inventory/recipes'],
    estimatedReadMinutes: 3,
    steps: [
      {
        number: 1,
        title: 'Target Benchmarks',
        instruction: 'Green (< 30%): Exceptional profitability. Amber (30–38%): Standard hospitality range. Red (> 38%): High food cost; consider portion adjustments.',
      },
    ],
    relatedArticles: ['recipe-quick-start', 'calculating-cogs-and-profitability'],
  },
  {
    slug: 'sub-recipes-and-prep-production',
    title: 'Sub-Recipes & Prep Batch Production',
    description: 'How to create prepared ingredients (sauces, dressings, prepped cuts) and produce batches with raw stock deduction.',
    category: 'inventory-management',
    keywords: ['sub-recipes', 'prep batch', 'production', 'kitchen prep'],
    allowedRoles: ['business_owner', 'branch_manager', 'kitchen_staff'],
    requiredPermissions: ['inventory.production.manage'],
    contextRoutes: ['/dashboard/inventory/production'],
    estimatedReadMinutes: 4,
    steps: [
      {
        number: 1,
        title: 'Set Recipe Type to Prep / Sub-Recipe',
        instruction: 'When creating the recipe, choose "Prep / Sub-Recipe" and select the output inventory stock item.',
      },
      {
        number: 2,
        title: 'Produce Batch',
        instruction: 'Under Prep Production, select the recipe, set the scale multiplier, and click "Dispatch Production" to deduct raw items and create prepared stock.',
      },
    ],
    relatedArticles: ['kitchen-yield-and-variance', 'creating-recipes-and-bom'],
    directAction: { label: 'Go to Prep Production', href: '/dashboard/inventory/production' },
  },
  {
    slug: 'kitchen-yield-and-variance',
    title: 'Kitchen Trimming Yield & Production Variance',
    description: 'Understanding yield factors on raw meats/produce and tracking production variances when batch output differs from expected.',
    category: 'inventory-management',
    keywords: ['yield', 'trimming loss', 'batch variance', 'production discrepancy'],
    allowedRoles: ['business_owner', 'branch_manager'],
    requiredPermissions: ['inventory.production.manage'],
    contextRoutes: ['/dashboard/inventory/production'],
    estimatedReadMinutes: 3,
    steps: [
      {
        number: 1,
        title: 'Yield Trimming Factor',
        instruction: 'If 10kg chicken yields 8.8kg usable breast after deboning, set 88% yield. WSNexa factors in the cost of trim automatically.',
      },
    ],
    relatedArticles: ['sub-recipes-and-prep-production'],
  },
  {
    slug: 'automatic-stock-deduction-timing',
    title: 'Automatic Stock Deduction Timing',
    description: 'Configure when ingredients are deducted from storage locations during the order lifecycle.',
    category: 'inventory-management',
    keywords: ['stock deduction', 'deduction timing', 'kitchen preparing', 'order confirmed'],
    allowedRoles: ['business_owner', 'branch_manager'],
    requiredPermissions: ['inventory.settings.manage'],
    contextRoutes: ['/dashboard/inventory/settings'],
    estimatedReadMinutes: 3,
    steps: [
      {
        number: 1,
        title: 'Recommended: When Kitchen Starts Preparing',
        instruction: 'Deduct stock when cooks begin preparation. Reflects real-time food commitment.',
      },
    ],
    relatedArticles: ['modifier-inventory-consumption'],
    directAction: { label: 'Configure Settings', href: '/dashboard/inventory/settings' },
  },
  {
    slug: 'modifier-inventory-consumption',
    title: 'Modifier Inventory Effects',
    description: 'How customer customizations (extra cheese, no onions, double protein) adjust ingredient consumption deltas.',
    category: 'inventory-management',
    keywords: ['modifiers', 'customization', 'extra ingredient', 'modifier stock'],
    allowedRoles: ['business_owner', 'branch_manager'],
    requiredPermissions: ['recipes.manage'],
    contextRoutes: ['/dashboard/inventory/recipes'],
    estimatedReadMinutes: 3,
    steps: [
      {
        number: 1,
        title: 'Modifier Deltas',
        instruction: 'When guests choose "Extra Cheese", WSNexa increases consumption according to modifier rules.',
      },
    ],
    relatedArticles: ['automatic-stock-deduction-timing'],
  },
  {
    slug: 'supplier-management',
    title: 'Supplier & Vendor Directory',
    description: 'Managing supplier records, contact information, payment terms, and item SKU mappings.',
    category: 'inventory-management',
    keywords: ['suppliers', 'vendors', 'procurement', 'vendor terms'],
    allowedRoles: ['business_owner', 'branch_manager'],
    requiredPermissions: ['suppliers.view'],
    contextRoutes: ['/dashboard/inventory/suppliers'],
    estimatedReadMinutes: 3,
    steps: [
      {
        number: 1,
        title: 'Add Suppliers',
        instruction: 'Register vendors with contact info, default payment terms, and preferred status under Suppliers.',
      },
    ],
    relatedArticles: ['creating-purchase-orders', 'receiving-goods-and-grn'],
    directAction: { label: 'Go to Suppliers', href: '/dashboard/inventory/suppliers' },
  },
  {
    slug: 'creating-purchase-orders',
    title: 'Creating & Approving Purchase Orders',
    description: 'Drafting purchase orders, managing procurement approvals, and sending orders to vendors.',
    category: 'inventory-management',
    keywords: ['purchase orders', 'po', 'procurement', 'approvals'],
    allowedRoles: ['business_owner', 'branch_manager'],
    requiredPermissions: ['purchasing.create'],
    contextRoutes: ['/dashboard/inventory/purchasing', '/dashboard/inventory/purchasing/new'],
    estimatedReadMinutes: 3,
    steps: [
      {
        number: 1,
        title: 'Create Purchase Order',
        instruction: 'Select the vendor, destination storage location, and line items with purchasing units and unit costs.',
      },
      {
        number: 2,
        title: 'Approve & Dispatch',
        instruction: 'Authorized managers review and approve the draft PO before dispatch.',
      },
    ],
    relatedArticles: ['receiving-goods-and-grn', 'supplier-management'],
    directAction: { label: 'Go to Purchase Orders', href: '/dashboard/inventory/purchasing' },
  },
  {
    slug: 'receiving-goods-and-grn',
    title: 'Receiving Goods & Stock Deliveries (GRN)',
    description: 'Accepting supplier shipments, recording actual quantities and batch expiry, and updating weighted average costs.',
    category: 'inventory-management',
    keywords: ['receiving', 'grn', 'goods received', 'weighted average cost', 'batch expiry'],
    allowedRoles: ['business_owner', 'branch_manager'],
    requiredPermissions: ['purchasing.receive'],
    contextRoutes: ['/dashboard/inventory/receiving'],
    estimatedReadMinutes: 4,
    steps: [
      {
        number: 1,
        title: 'Open Receive Goods',
        instruction: 'Select the incoming Purchase Order (or select direct delivery) on your tablet or computer.',
      },
      {
        number: 2,
        title: 'Enter Delivered Quantities',
        instruction: 'Verify count, input actual unit costs, and add batch codes and expiry dates.',
      },
      {
        number: 3,
        title: 'Receive Stock',
        instruction: 'Click "Receive Delivery". WSNexa atomically increases stock balances and recalculates weighted average costs.',
      },
    ],
    relatedArticles: ['partial-and-discrepancy-receiving', 'creating-purchase-orders'],
    directAction: { label: 'Receive Goods', href: '/dashboard/inventory/receiving' },
  },
  {
    slug: 'partial-and-discrepancy-receiving',
    title: 'Partial Deliveries & Discrepancy Tolerances',
    description: 'How to handle short-shipments, over-deliveries, and multiple partial delivery receipts against a single PO.',
    category: 'inventory-management',
    keywords: ['partial delivery', 'discrepancy', 'over-receiving', 'short shipment'],
    allowedRoles: ['business_owner', 'branch_manager'],
    requiredPermissions: ['purchasing.receive'],
    contextRoutes: ['/dashboard/inventory/receiving'],
    estimatedReadMinutes: 3,
    steps: [
      {
        number: 1,
        title: 'Partial Receiving',
        instruction: 'Receive available items today; the PO status moves to "Partially Received" and remains open for remaining items.',
      },
    ],
    relatedArticles: ['receiving-goods-and-grn'],
  },
  {
    slug: 'calculating-cogs-and-profitability',
    title: 'Calculating COGS & Food Margins',
    description: 'How historical recipe consumption snapshots power accurate Cost of Goods Sold (COGS) reporting without price distortion.',
    category: 'inventory-management',
    keywords: ['cogs', 'cost of goods sold', 'gross margin', 'financial reports'],
    allowedRoles: ['business_owner', 'branch_manager'],
    requiredPermissions: ['inventory.cogs.view'],
    contextRoutes: ['/dashboard/reports'],
    estimatedReadMinutes: 4,
    steps: [
      {
        number: 1,
        title: 'Immutable Snapshots',
        instruction: 'When orders are consumed, the exact ingredient cost at that moment is locked into the consumption ledger, guaranteeing accurate historical COGS.',
      },
    ],
    relatedArticles: ['menu-engineering-matrix', 'understanding-food-cost-and-margins'],
  },
  {
    slug: 'theoretical-vs-actual-stock-variance',
    title: 'Theoretical vs. Actual Stock & Variance Analysis',
    description: 'Comparing expected ledger balances against physical stock counts to identify portion drift or unrecorded waste.',
    category: 'inventory-management',
    keywords: ['theoretical stock', 'actual stock', 'variance', 'reconciliation'],
    allowedRoles: ['business_owner', 'branch_manager'],
    requiredPermissions: ['inventory.counts.manage'],
    contextRoutes: ['/dashboard/inventory/counts'],
    estimatedReadMinutes: 3,
    steps: [
      {
        number: 1,
        title: 'Theoretical Calculation',
        instruction: 'Opening Stock + Purchases - Recipe Consumption - Waste = Theoretical Stock.',
      },
    ],
    relatedArticles: ['calculating-cogs-and-profitability'],
  },
  {
    slug: 'menu-engineering-matrix',
    title: 'Menu Engineering: Stars, Plowhorses, Puzzles & Dogs',
    description: 'Using the Boston Consulting Group / Miller matrix to optimize menu item popularity and profitability.',
    category: 'inventory-management',
    keywords: ['menu engineering', 'stars', 'plowhorses', 'puzzles', 'dogs', 'menu matrix'],
    allowedRoles: ['business_owner', 'branch_manager'],
    requiredPermissions: ['inventory.menu_profitability.view'],
    contextRoutes: ['/dashboard/reports'],
    estimatedReadMinutes: 4,
    steps: [
      {
        number: 1,
        title: 'Stars 🌟 (High Sales, High Margin)',
        instruction: 'Keep quality and recipes consistent.',
      },
      {
        number: 2,
        title: 'Plowhorses 🐎 (High Sales, Lower Margin)',
        instruction: 'Optimize ingredient portioning or adjust price slightly.',
      },
      {
        number: 3,
        title: 'Puzzles 🧩 (Low Sales, High Margin)',
        instruction: 'Promote actively with waiter suggestions.',
      },
      {
        number: 4,
        title: 'Dogs 🐕 (Low Sales, Low Margin)',
        instruction: 'Reformulate or remove from menu.',
      },
    ],
    relatedArticles: ['calculating-cogs-and-profitability'],
  },
];

