import { HelpArticle } from '../types';

export const inventoryArticles: HelpArticle[] = [
  {
    slug: 'inventory-basics-stock-items',
    title: 'Inventory Basics: Adding Stock Items & Units',
    titleSiEn: 'Inventory මූලික කරුණු: Stock Items සහ Units එකතු කිරීම',
    description: 'Learn how to register raw food ingredients, packaging materials, base units (kg, L, pcs), and set reorder alerts.',
    descriptionSiEn: 'අමුද්‍රව්‍ය, මිනුම් ඒකක (kg, L, pcs), මිලදී ගැනීමේ මිල සහ Low Stock Alerts සකස් කරන ආකාරය.',
    category: 'inventory-management',
    keywords: ['inventory', 'stock items', 'ingredients', 'raw materials', 'reorder level', 'units'],
    popular: true,
    contextRoutes: ['/dashboard/inventory', '/dashboard/inventory/items', '/dashboard/inventory/items/new'],
    estimatedReadMinutes: 4,
    steps: [
      {
        number: 1,
        title: 'Open Stock Items',
        titleSiEn: 'Stock Items වෙත යන්න',
        instruction: 'From the dashboard sidebar, navigate to Operations → Stock Items (/dashboard/inventory/items).',
        instructionSiEn: 'Dashboard sidebar එකෙන් Operations → Stock Items (/dashboard/inventory/items) වෙත යන්න.',
      },
      {
        number: 2,
        title: 'Add Stock Item',
        titleSiEn: 'Stock Item එකක් එකතු කරන්න',
        instruction: 'Click "+ Add Stock Item". Enter Item Name (e.g. "Chicken Breast", "Mozzarella Cheese"), Unit of Measure (kg/g/L/ml/pcs), and Cost per Unit.',
        instructionSiEn: '+ Add Stock Item click කරන්න. Item Name (උදා. "Chicken Breast", "Mozzarella"), Unit (kg, L, pcs) සහ Cost per Unit ඇතුළත් කරන්න.',
      },
      {
        number: 3,
        title: 'Set Reorder Threshold & Save',
        titleSiEn: 'Reorder Level එක සකසා Save කරන්න',
        instruction: 'Set the minimum stock alert level (e.g. 5 kg) so WSNexa warns you before ingredients run out. Click Save.',
        instructionSiEn: 'අමුද්‍රව්‍ය අවසන් වීමට පෙර alert ලැබීමට Reorder Level (උදා. 5 kg) එකක් සකසා Save කරන්න.',
      },
    ],
    notes: [
      'Stock items belong to the business but current inventory balances are tracked per branch and storage location.',
    ],
    notesSiEn: [
      'Stock item නම් business මට්ටමින් නිර්මාණය වන අතර, ප්‍රමාණයන් (quantities) එක් එක් branch එක අනුව වෙන් වෙන්ව පාලනය වේ.',
    ],
    relatedArticles: ['recipes-and-bill-of-materials', 'managing-suppliers', 'purchase-orders-and-receiving'],
    directAction: {
      label: 'Open Stock Items',
      labelSiEn: 'Stock Items වෙත යන්න',
      href: '/dashboard/inventory/items',
    },
  },
  {
    slug: 'recipes-and-bill-of-materials',
    title: 'How to Build Recipes & Bill of Materials (BOM)',
    titleSiEn: 'Recipes සහ Bill of Materials (BOM) සකස් කරන්නේ කෙසේද?',
    description: 'Link raw inventory ingredients to menu dishes for automated stock depletion and food cost profit margin calculations.',
    descriptionSiEn: 'Menu item එකක් order වූ විට අදාළ අමුද්‍රව්‍ය ස්වයංක්‍රීයව අඩු වන පරිදි Recipe එකක් සැකසීම.',
    category: 'inventory-management',
    keywords: ['recipes', 'bom', 'bill of materials', 'food cost', 'cogs', 'auto deduction'],
    contextRoutes: ['/dashboard/inventory/recipes', '/dashboard/inventory/recipes/new'],
    estimatedReadMinutes: 4,
    steps: [
      {
        number: 1,
        title: 'Navigate to Recipes & BOM',
        titleSiEn: 'Recipes & BOM වෙත යන්න',
        instruction: 'From Operations in the sidebar, click Recipes & BOM (/dashboard/inventory/recipes).',
        instructionSiEn: 'Sidebar එකෙහි Operations යටතේ ඇති Recipes & BOM (/dashboard/inventory/recipes) වෙත යන්න.',
      },
      {
        number: 2,
        title: 'Create Recipe for Menu Item',
        titleSiEn: 'Menu Item එකට Recipe එකක් සාදන්න',
        instruction: 'Click "+ Create Recipe". Select the target Menu Item (e.g. "Chicken Burger").',
        instructionSiEn: '+ Create Recipe click කර අදාළ Menu Item එක (උදා. "Chicken Burger") තෝරන්න.',
      },
      {
        number: 3,
        title: 'Add Ingredients & Quantities',
        titleSiEn: 'අමුද්‍රව්‍ය සහ ප්‍රමාණයන් එක් කරන්න',
        instruction: 'Add required ingredients (e.g. "Chicken Breast 150g", "Burger Bun 1 pcs", "Cheese Slice 1 pcs"). WSNexa calculates the exact dish Cost of Goods Sold (COGS).',
        instructionSiEn: 'අවශ්‍ය අමුද්‍රව්‍ය එක් කරන්න (උදා. "Chicken 150g", "Bun 1 pcs"). පද්ධතිය විසින් dish එකෙහි Cost of Goods Sold (COGS) ගණනය කර පෙන්වයි.',
      },
    ],
    relatedArticles: ['inventory-basics-stock-items', 'purchase-orders-and-receiving'],
    directAction: {
      label: 'Open Recipes',
      labelSiEn: 'Recipes වෙත යන්න',
      href: '/dashboard/inventory/recipes',
    },
  },
  {
    slug: 'managing-suppliers',
    title: 'How to Manage Ingredient Suppliers & Vendor Profiles',
    titleSiEn: 'Suppliers සහ Vendor Profiles කළමනාකරණය කරන්නේ කෙසේද?',
    description: 'Keep vendor contact books, payment terms, delivery lead times, and linked purchase supplies.',
    descriptionSiEn: 'අමුද්‍රව්‍ය සපයන Suppliers ගේ විස්තර, දුරකථන අංක සහ Payment Terms සටහන් කර තබාගැනීම.',
    category: 'inventory-management',
    keywords: ['suppliers', 'vendors', 'supplier directory', 'lead time', 'procurement'],
    contextRoutes: ['/dashboard/inventory/suppliers'],
    estimatedReadMinutes: 3,
    steps: [
      {
        number: 1,
        title: 'Go to Suppliers Directory',
        titleSiEn: 'Suppliers Directory වෙත යන්න',
        instruction: 'Navigate to Operations → Suppliers (/dashboard/inventory/suppliers).',
        instructionSiEn: 'Operations → Suppliers (/dashboard/inventory/suppliers) වෙත යන්න.',
      },
      {
        number: 2,
        title: 'Create Supplier Record',
        titleSiEn: 'Supplier Record එකක් create කරන්න',
        instruction: 'Click "+ Add Supplier". Enter Supplier Name, Contact Person, Email, Phone, and Payment Terms (e.g. "Net 30").',
        instructionSiEn: '+ Add Supplier click කර Supplier Name, Contact Person, Phone සහ Payment Terms ඇතුළත් කරන්න.',
      },
    ],
    relatedArticles: ['purchase-orders-and-receiving', 'inventory-basics-stock-items'],
    directAction: {
      label: 'Open Suppliers',
      labelSiEn: 'Suppliers වෙත යන්න',
      href: '/dashboard/inventory/suppliers',
    },
  },
  {
    slug: 'purchase-orders-and-receiving',
    title: 'How to Create Purchase Orders & Receive Goods (GRN)',
    titleSiEn: 'Purchase Orders (PO) සෑදීම සහ Goods Receiving (GRN) කිරීම',
    description: 'Issue formal purchase orders to suppliers and record incoming deliveries to increase inventory on-hand balances.',
    descriptionSiEn: 'Suppliers වෙත Purchase Orders යැවීම සහ ඇණවුම් ලැබුණු පසු Goods Received Note (GRN) මඟින් stock වැඩි කිරීම.',
    category: 'inventory-management',
    keywords: ['purchase orders', 'po', 'grn', 'goods receiving', 'procurement', 'restock'],
    contextRoutes: ['/dashboard/inventory/purchasing', '/dashboard/inventory/receiving'],
    estimatedReadMinutes: 4,
    steps: [
      {
        number: 1,
        title: 'Create Purchase Order (PO)',
        titleSiEn: 'Purchase Order එකක් සාදන්න',
        instruction: 'Go to Operations → Purchasing (/dashboard/inventory/purchasing). Click "+ New Purchase Order", select the Supplier, and add order items with unit costs.',
        instructionSiEn: 'Operations → Purchasing වෙත ගොස් "+ New Purchase Order" click කරන්න. Supplier තෝරා අවශ්‍ය අමුද්‍රව්‍ය ප්‍රමාණ ඇතුළත් කරන්න.',
      },
      {
        number: 2,
        title: 'Receive Goods Delivery (GRN)',
        titleSiEn: 'භාණ්ඩ ලැබුණු විට Receive කරන්න (GRN)',
        instruction: 'When the delivery arrives, click "Receive Goods" on the PO, verify actual delivered quantities, and confirm. Your stock counts update automatically.',
        instructionSiEn: 'භාණ්ඩ ලැබුණු විට PO එකෙහි "Receive Goods" click කර ලැබුණු ප්‍රමාණ තහවුරු කරන්න. Stock ප්‍රමාණයන් ස්වයංක්‍රීයව වැඩිවේ.',
      },
    ],
    relatedArticles: ['managing-suppliers', 'inventory-basics-stock-items', 'physical-stock-counts'],
    directAction: {
      label: 'Open Purchasing',
      labelSiEn: 'Purchasing වෙත යන්න',
      href: '/dashboard/inventory/purchasing',
    },
  },
  {
    slug: 'stock-transfers-between-locations',
    title: 'How to Transfer Stock Between Storage Locations & Branches',
    titleSiEn: 'Storage Locations සහ Branches අතර Stock Transfer කරන්නේ කෙසේද?',
    description: 'Move ingredients between Main Stock, Cold Room, Kitchen, and Bar with formal dispatch and receiving confirmation.',
    descriptionSiEn: 'Main Warehouse එකෙන් Kitchen, Bar හෝ වෙනත් Branch එකකට අමුද්‍රව්‍ය මාරු කිරීම.',
    category: 'inventory-management',
    keywords: ['transfers', 'stock transfer', 'internal transfer', 'inter branch'],
    contextRoutes: ['/dashboard/inventory/transfers'],
    estimatedReadMinutes: 3,
    steps: [
      {
        number: 1,
        title: 'Initiate Stock Transfer',
        titleSiEn: 'Stock Transfer එකක් ආරම්භ කරන්න',
        instruction: 'Go to Operations → Stock Transfers (/dashboard/inventory/transfers). Click "+ New Transfer".',
        instructionSiEn: 'Operations → Stock Transfers වෙත ගොස් "+ New Transfer" click කරන්න.',
      },
      {
        number: 2,
        title: 'Select Source & Destination',
        titleSiEn: 'Source සහ Destination තෝරන්න',
        instruction: 'Choose origin location (e.g. "Main Store") and destination (e.g. "Bar Store"). Add item quantities and click Dispatch.',
        instructionSiEn: 'නිකුත් කරන ස්ථානය (උදා. "Main Store") සහ ලැබෙන ස්ථානය (උදා. "Bar Store") තෝරා Dispatch කරන්න.',
      },
    ],
    relatedArticles: ['inventory-basics-stock-items', 'physical-stock-counts'],
    directAction: {
      label: 'Open Stock Transfers',
      labelSiEn: 'Stock Transfers වෙත යන්න',
      href: '/dashboard/inventory/transfers',
    },
  },
  {
    slug: 'physical-stock-counts',
    title: 'How to Perform Physical Stock Counts & Audits',
    titleSiEn: 'Physical Stock Counts සහ Audits සිදුකරන්නේ කෙසේද?',
    description: 'Perform scheduled stock takes, enter physical counts, and reconcile inventory discrepancies with approval controls.',
    descriptionSiEn: 'සත්‍ය වශයෙන්ම පවතින අමුද්‍රව්‍ය ප්‍රමාණ ගණනය කර පද්ධතියේ ඇති ප්‍රමාණයන් සමඟ සංසන්දනය කිරීම (Stock Audit).',
    category: 'inventory-management',
    keywords: ['stock count', 'stock take', 'audit', 'variance', 'inventory reconciliation'],
    contextRoutes: ['/dashboard/inventory/counts'],
    estimatedReadMinutes: 3,
    steps: [
      {
        number: 1,
        title: 'Start a Stock Count Session',
        titleSiEn: 'Stock Count Session එකක් ආරම්භ කරන්න',
        instruction: 'Go to Operations → Stock Counts (/dashboard/inventory/counts). Click "+ New Stock Count" and select the storage location.',
        instructionSiEn: 'Operations → Stock Counts වෙත ගොස් "+ New Stock Count" click කර ගබඩාව තෝරන්න.',
      },
      {
        number: 2,
        title: 'Enter Counted Quantities & Submit',
        titleSiEn: 'ගණනය කළ ප්‍රමාණ ඇතුළත් කර Submit කරන්න',
        instruction: 'Count physical stock on shelves, enter numbers, and click "Submit for Approval". Manager approves to update system balances.',
        instructionSiEn: 'සත්‍ය ප්‍රමාණ ගණනය කර ඇතුළත් කරන්න. Manager විසින් approve කළ පසු පද්ධතියේ balances නිවැරදි වේ.',
      },
    ],
    relatedArticles: ['waste-and-stock-adjustments', 'inventory-basics-stock-items'],
    directAction: {
      label: 'Open Stock Counts',
      labelSiEn: 'Stock Counts වෙත යන්න',
      href: '/dashboard/inventory/counts',
    },
  },
  {
    slug: 'waste-and-stock-adjustments',
    title: 'How to Record Spoilage, Waste & Stock Adjustments',
    titleSiEn: 'Spoilage, Waste සහ Stock Adjustments සටහන් කරන්නේ කෙසේද?',
    description: 'Log kitchen prep waste, expired food items, broken bottles, and adjust stock counts with reason codes.',
    descriptionSiEn: 'කල් ඉකුත් වූ, නරක් වූ හෝ හානි වූ අමුද්‍රව්‍ය Waste ලෙස පද්ධතියට සටහන් කිරීම.',
    category: 'inventory-management',
    keywords: ['waste', 'spoilage', 'damaged goods', 'stock adjustment', 'loss'],
    contextRoutes: ['/dashboard/inventory/waste'],
    estimatedReadMinutes: 3,
    steps: [
      {
        number: 1,
        title: 'Navigate to Waste Logging',
        titleSiEn: 'Waste Logging වෙත යන්න',
        instruction: 'Go to Operations → Waste & Loss (/dashboard/inventory/waste). Click "+ Log Waste".',
        instructionSiEn: 'Operations → Waste & Loss වෙත ගොස් "+ Log Waste" click කරන්න.',
      },
      {
        number: 2,
        title: 'Select Item, Quantity & Reason',
        titleSiEn: 'Item, Quantity සහ Reason තෝරන්න',
        instruction: 'Select ingredient, enter wasted quantity, and choose reason code (e.g. "Expired", "Burnt in Kitchen", "Spill"). Click Confirm.',
        instructionSiEn: 'අමුද්‍රව්‍ය, ප්‍රමාණය සහ හේතුව (උදා. "Expired", "Burnt", "Spill") තෝරා Confirm කරන්න.',
      },
    ],
    relatedArticles: ['physical-stock-counts', 'inventory-basics-stock-items'],
    directAction: {
      label: 'Open Waste Log',
      labelSiEn: 'Waste Log වෙත යන්න',
      href: '/dashboard/inventory/waste',
    },
  },
];
