import { HelpArticle } from '../types';

export const MENU_MANAGEMENT_ARTICLES: HelpArticle[] = [
  {
    slug: 'create-categories',
    title: 'How to Create and Organize Menu Categories',
    titleSiEn: 'Menu Categories සාදා පිළිවෙලට සකස් කරන්නේ කෙසේද?',
    description: 'Create organized menu sections like Appetizers, Main Courses, Desserts, Cocktails, and Hot Beverages.',
    descriptionSiEn: 'Appetizers, Main Courses, Desserts, Beverages වැනි කාණ්ඩ අනුව menu එක පිළිවෙලට බෙදා වෙන් කිරීම.',
    category: 'menu-management',
    keywords: ['categories', 'menu sections', 'menu categories', 'appetizers', 'beverages'],
    popular: true,
    contextRoutes: ['/dashboard/menu/categories', '/dashboard/menu'],
    estimatedReadMinutes: 3,
    steps: [
      {
        number: 1,
        title: 'Go to Menu Categories',
        titleSiEn: 'Menu Categories වෙත යන්න',
        instruction: 'From the dashboard sidebar, click Menu → Categories (/dashboard/menu/categories).',
        instructionSiEn: 'Dashboard sidebar එකෙන් Menu → Categories (/dashboard/menu/categories) වෙත යන්න.',
      },
      {
        number: 2,
        title: 'Create a Category',
        titleSiEn: 'Category එකක් create කරන්න',
        instruction: 'Click "+ Create Category". Enter the Category Name (e.g. "Main Dishes") and optional description.',
        instructionSiEn: '+ Create Category button එක click කරන්න. Category Name එක (උදා. "Main Dishes") ඇතුළත් කරන්න.',
      },
      {
        number: 3,
        title: 'Create and Manage Order',
        titleSiEn: 'Create කර Category අනුපිළිවෙල සකසන්න',
        instruction: 'Click "+ Create Category". Re-order or edit categories anytime from the category management list.',
        instructionSiEn: '"+ Create Category" click කර save කරන්න. Category management list එකෙන් ඕනෑම වේලාවක සංස්කරණය කළ හැක.',
      },
    ],
    notes: [
      'You must create at least one category before adding menu items.',
    ],
    notesSiEn: [
      'Menu Items එක් කිරීමට පෙර අවම වශයෙන් එක් Category එකක්වත් සෑදිය යුතුය.',
    ],
    relatedArticles: ['add-menu-items', 'configure-modifiers'],
    directAction: {
      label: 'Open Categories',
      labelSiEn: 'Categories වෙත යන්න',
      href: '/dashboard/menu/categories',
    },
  },
  {
    slug: 'add-menu-items',
    title: 'How to Add and Manage Menu Items',
    titleSiEn: 'Menu Items එකතු කිරීම සහ කළමනාකරණය කරන්නේ කෙසේද?',
    description: 'Add dishes, drinks, set prices, upload food photos, add descriptions, and assign to categories.',
    descriptionSiEn: 'කෑම සහ බීම වර්ග, මිල ගණන්, ඡායාරූප, විස්තර ඇතුළත් කර categories වලට assign කරන ආකාරය.',
    category: 'menu-management',
    keywords: ['menu items', 'add dish', 'food pricing', 'dish photos', 'dishes', 'beverages'],
    popular: true,
    contextRoutes: ['/dashboard/menu/items', '/dashboard/menu/items/new'],
    estimatedReadMinutes: 4,
    steps: [
      {
        number: 1,
        title: 'Navigate to Menu Items',
        titleSiEn: 'Menu Items වෙත යන්න',
        instruction: 'From the dashboard sidebar, navigate to Menu → Items (/dashboard/menu/items).',
        instructionSiEn: 'Dashboard sidebar එකෙන් Menu → Items (/dashboard/menu/items) වෙත යන්න.',
      },
      {
        number: 2,
        title: 'Create Menu Item',
        titleSiEn: 'New Item එකක් create කරන්න',
        instruction: 'Click "+ Add Menu Item". Select the target Category, enter the Item Name, Selling Price, and Description.',
        instructionSiEn: '+ Add Menu Item button එක click කරන්න. අදාළ Category එක තෝරා Item Name, Selling Price සහ Description ඇතුළත් කරන්න.',
      },
      {
        number: 3,
        title: 'Upload Food Image and Save',
        titleSiEn: 'Image එකක් upload කර Save කරන්න',
        instruction: 'Optionally upload a dish image and click "Add Menu Item" (or "Save & Add Another +") to save the item.',
        instructionSiEn: 'කෑමෙහි image එකක් upload කර "Add Menu Item" (හෝ "Save & Add Another +") click කර save කරන්න.',
      },
    ],

    relatedArticles: ['create-categories', 'configure-modifiers', 'menu-availability-sold-out'],
    directAction: {
      label: 'Add Menu Item',
      labelSiEn: 'Menu Item එකතු කරන්න',
      href: '/dashboard/menu/items/new',
    },
  },
  {
    slug: 'configure-modifiers',
    title: 'How to Configure Modifiers, Options & Add-ons',
    titleSiEn: 'Modifiers, Add-ons සහ Options සකස් කරන්නේ කෙසේද?',
    description: 'Set up customizations like Spice Level (Mild, Medium, Spicy), Portion Sizes (Regular, Large), and Extra Add-ons (Cheese, Sauce).',
    descriptionSiEn: 'Spice Levels (Mild/Spicy), Portion Sizes (Regular/Large) හෝ Extra Cheese වැනි Add-ons කෑම සඳහා සකස් කිරීම.',
    category: 'menu-management',
    keywords: ['modifiers', 'addons', 'customizations', 'portion sizes', 'spice levels', 'options'],
    contextRoutes: ['/dashboard/menu/items'],
    estimatedReadMinutes: 4,
    steps: [
      {
        number: 1,
        title: 'Select Item to Customize',
        titleSiEn: 'Item එකෙහි Modifiers තෝරන්න',
        instruction: 'Go to Menu → Items and click "Modifiers" on the specific menu item.',
        instructionSiEn: 'Menu → Items වෙත ගොස් අදාළ item එක අසල ඇති Modifiers button එක click කරන්න.',
      },
      {
        number: 2,
        title: 'Create Modifier Group',
        titleSiEn: 'Modifier Group එකක් සාදන්න',
        instruction: 'Create a group such as "Choose Size" (Single Choice / Required) or "Extra Toppings" (Multiple Choice / Optional).',
        instructionSiEn: '"Choose Size" (Single Choice / Required) හෝ "Extra Toppings" (Multiple Choice / Optional) ලෙස group එකක් සාදන්න.',
      },
      {
        number: 3,
        title: 'Add Options with Extra Prices',
        titleSiEn: 'මිල ගණන් සහිතව Options එක් කරන්න',
        instruction: 'Add options (e.g. "Extra Cheese +$1.50", "Regular +$0.00"). Click Save Changes.',
        instructionSiEn: 'Options එක් කරන්න (උදා. "Extra Cheese +$1.50"). Save Changes click කරන්න.',
      },
    ],
    relatedArticles: ['add-menu-items', 'create-categories'],
    directAction: {
      label: 'Manage Menu Items',
      labelSiEn: 'Menu Items කළමනාකරණය',
      href: '/dashboard/menu/items',
    },
  },
  {
    slug: 'menu-availability-sold-out',
    title: 'Managing Item Availability & Sold-Out Status',
    titleSiEn: 'Item Availability සහ Sold Out තත්ත්වය පාලනය කිරීම',
    description: 'Quickly mark dishes as sold out or disable seasonal items so customers cannot order them.',
    descriptionSiEn: 'අමුද්‍රව්‍ය අවසන් වූ විට ක්ෂණිකව item එකක් Sold Out ලෙස සලකුණු කිරීම හෝ ತಾත්කාලිකව disable කිරීම.',
    category: 'menu-management',
    keywords: ['sold out', 'item availability', 'out of stock', 'disable dish', 'menu toggle'],
    contextRoutes: ['/dashboard/menu/items'],
    estimatedReadMinutes: 2,
    steps: [
      {
        number: 1,
        title: 'Locate Item in Menu',
        titleSiEn: 'Menu Item එක සොයාගන්න',
        instruction: 'Navigate to Menu → Items. Find the item using the search bar or category filter.',
        instructionSiEn: 'Menu → Items වෙත ගොස් search bar එකෙන් අදාළ item එක සොයාගන්න.',
      },
      {
        number: 2,
        title: 'Toggle Availability Switch',
        titleSiEn: 'Availability Toggle switch එක මාරු කරන්න',
        instruction: 'Toggle the "Available" switch to OFF. The item immediately shows as "Sold Out" on all QR menus and Waiter screens.',
        instructionSiEn: 'Available switch එක OFF කරන්න. ක්ෂණිකව QR මෙනුවල සහ Waiter screens වල එම item එක "Sold Out" ලෙස පෙන්වයි.',
      },
    ],
    relatedArticles: ['add-menu-items', 'create-categories'],
    directAction: {
      label: 'View Menu Items',
      labelSiEn: 'Menu Items බලන්න',
      href: '/dashboard/menu/items',
    },
  },
];
