import { HelpArticle } from '../types';

export const ORDER_SECURITY_ARTICLES: HelpArticle[] = [
  {
    slug: 'order-security-overview',
    title: 'Order Security & Anti-Fraud Protection Explained',
    titleSiEn: 'Order Security සහ වංචනික Orders වැළැක්වීමේ ක්‍රමවේදය',
    description: 'Protect your kitchen from prank orders and unauthorized remote scans with WSNexa multi-layer security.',
    descriptionSiEn: 'දුරස්ථව සිදුවන ව්‍යාජ orders සහ අනවශ්‍ය ඇණවුම් වැළැක්වීම සඳහා ඇති බහු-ස්ථර ආරක්ෂක විධිවිධාන.',
    category: 'order-security',
    keywords: ['order security', 'anti-fraud', 'security settings', 'protection', 'table pin', 'waiter approval'],
    popular: true,
    contextRoutes: ['/dashboard/settings/order-security'],
    estimatedReadMinutes: 3,
    steps: [
      {
        number: 1,
        title: 'Open Order Security Hub',
        titleSiEn: 'Order Security Hub එක open කරන්න',
        instruction: 'Go to Settings → Order Security (/dashboard/settings/order-security).',
        instructionSiEn: 'Settings → Order Security (/dashboard/settings/order-security) වෙත යන්න.',
      },
      {
        number: 2,
        title: 'Choose Your Security Level',
        titleSiEn: 'ආරක්ෂක මට්ටම තෝරන්න',
        instruction: 'Choose whether you want lightweight frictionless ordering (open QR) or strict physical verification (Table PINs + Waiter Approval).',
        instructionSiEn: 'ඉක්මන් ordering සඳහා open QR ද, නැතහොත් වැඩි ආරක්ෂාවක් සඳහා Table PINs හෝ Waiter Approval ද යන්න තෝරන්න.',
      },
      {
        number: 3,
        title: 'Save Branch Security Rules',
        titleSiEn: 'Security Rules Save කරන්න',
        instruction: 'Click "💾 Save Security Settings". All QR customer sessions adhere immediately to your selected rules.',
        instructionSiEn: '"💾 Save Security Settings" click කරන්න. සියලුම QR customer sessions සඳහා මෙම නීති ක්ෂණිකව බලපැවැත්වේ.',
      },
    ],
    relatedArticles: ['waiter-approval-security-rule', 'table-pin-and-geofencing', 'customer-account-requirement'],
    directAction: {
      label: 'Open Order Security',
      labelSiEn: 'Order Security වෙත යන්න',
      href: '/dashboard/settings/order-security',
    },
  },
  {
    slug: 'waiter-approval-security-rule',
    title: 'How to Enable Waiter Approval Before Kitchen',
    titleSiEn: 'Waiter Approval Before Kitchen සක්‍රිය කරන්නේ කෙසේද?',
    description: 'Ensure food preparation never starts until floor waitstaff have physically visited the table to confirm the order.',
    descriptionSiEn: 'මේසය අසල සිටින වේටර් විසින් තහවුරු කරන තුරු Kitchen එකෙහි කෑම පිසීම ආරම්භ නොවන පරිදි සකසන ආකාරය.',
    category: 'order-security',
    keywords: ['waiter approval', 'gatekeeper', 'order verification', 'kitchen protection'],
    contextRoutes: ['/dashboard/settings/order-security'],
    estimatedReadMinutes: 2,
    steps: [
      {
        number: 1,
        title: 'Navigate to Order Security',
        titleSiEn: 'Order Security වෙත යන්න',
        instruction: 'Go to Settings → Order Security (/dashboard/settings/order-security).',
        instructionSiEn: 'Dashboard sidebar එකෙන් Settings → Order Security (/dashboard/settings/order-security) වෙත යන්න.',
      },
      {
        number: 2,
        title: 'Toggle Waiter Approval ON',
        titleSiEn: 'Waiter Approval toggle එක ON කරන්න',
        instruction: 'Find "Require Waiter Approval Before Kitchen" and switch the toggle to ON. Click "💾 Save Security Settings".',
        instructionSiEn: '"Require Waiter Approval Before Kitchen" switch එක ON කර "💾 Save Security Settings" click කරන්න.',
      },
    ],

    relatedArticles: ['order-security-overview', 'waiter-approval-before-kitchen'],
    directAction: {
      label: 'Configure Order Security',
      labelSiEn: 'Order Security සැකසීම',
      href: '/dashboard/settings/order-security',
    },
  },
  {
    slug: 'table-pin-and-geofencing',
    title: 'Configuring Table PINs & Geofence Boundaries',
    titleSiEn: 'Table PINs සහ Geofence Boundaries සැකසීම',
    description: 'Require customers to be physically seated at the table by verifying table PINs or checking GPS distance boundaries.',
    descriptionSiEn: 'පාරිභෝගිකයා මේසය අසලම සිටින බව තහවුරු කිරීමට Table PIN සහ GPS සීමාවන් යොදාගැනීම.',
    category: 'order-security',
    keywords: ['table pin', 'geofencing', 'gps radius', 'physical presence', 'radius'],
    contextRoutes: ['/dashboard/settings/order-security', '/dashboard/tables/qr'],
    estimatedReadMinutes: 3,
    steps: [
      {
        number: 1,
        title: 'Enable Require Table PIN',
        titleSiEn: 'Require Table PIN සක්‍රිය කරන්න',
        instruction: 'In Settings → Order Security, toggle "Require Table PIN" ON so guests must enter the PIN printed on the table tent.',
        instructionSiEn: 'Settings → Order Security හි "Require Table PIN" toggle එක ON කර මේසය මත ඇති PIN එක ඇතුළත් කිරීම අනිවාර්ය කරන්න.',
      },
      {
        number: 2,
        title: 'Set Geolocation Radius (Optional)',
        titleSiEn: 'Geolocation Radius එක සකසන්න (විකල්ප)',
        instruction: 'If your branch has GPS coordinates configured, set allowed radius (e.g. 100 meters) to block remote orders.',
        instructionSiEn: 'Branch GPS coordinates සකසා ඇත්නම්, මීටර් 100 ක් වැනි සීමාවක් ඇතුළත් කර දුර සිට දමන orders වළක්වන්න.',
      },
    ],
    relatedArticles: ['configure-table-pins', 'order-security-overview'],
    directAction: {
      label: 'Manage Order Security',
      labelSiEn: 'Order Security කළමනාකරණය',
      href: '/dashboard/settings/order-security',
    },
  },
  {
    slug: 'customer-account-requirement',
    title: 'Customer Account Requirements & Guest Ordering',
    titleSiEn: 'Customer Account අනිවාර්ය කිරීම සහ Guest Ordering',
    description: 'Decide whether customers can order anonymously as guests or must sign in with Google/Email to place orders.',
    descriptionSiEn: 'පාරිභෝගිකයින්ට Guest ලෙස ලොග් නොවී order කළ හැකිද නැතහොත් Login වීම අනිවාර්යද යන්න තේරීම.',
    category: 'order-security',
    keywords: ['customer login', 'guest checkout', 'account requirement', 'sign in'],
    contextRoutes: ['/dashboard/settings/order-security'],
    estimatedReadMinutes: 2,
    steps: [
      {
        number: 1,
        title: 'Review Customer Login Policy',
        titleSiEn: 'Customer Login Policy එක පරීක්ෂා කරන්න',
        instruction: 'In Settings → Order Security, review "Require Customer Login".',
        instructionSiEn: 'Settings → Order Security හි "Require Customer Login" විකල්පය බලන්න.',
      },
      {
        number: 2,
        title: 'Choose Guest vs Logged-In Mode',
        titleSiEn: 'Guest හෝ Logged-in තෝරන්න',
        instruction: 'Leave OFF for fastest guest checkout (recommended for fast dining). Toggle ON if you require verified customer emails.',
        instructionSiEn: 'වේගවත් ඇණවුම් සඳහා මෙය OFF කර තබන්න (Recommended). Verified emails අවශ්‍ය නම් පමණක් ON කරන්න.',
      },
    ],
    relatedArticles: ['order-security-overview', 'configuring-payment-methods'],
    directAction: {
      label: 'Open Order Security',
      labelSiEn: 'Order Security වෙත යන්න',
      href: '/dashboard/settings/order-security',
    },
  },
];
