import { HelpArticle } from '../types';

export const ORDERS_ARTICLES: HelpArticle[] = [
  {
    slug: 'how-customer-orders-flow',
    title: 'How Customer Orders Flow Through WSNexa',
    titleSiEn: 'Customer Orders පද්ධතිය තුළ ගලායන ආකාරය (Order Flow)',
    description: 'Understand the complete lifecycle of an order: from QR submission to waiter approval, kitchen preparation, and cashier settlement.',
    descriptionSiEn: 'QR order එකක් දැමූ මොහොතේ සිට Waiter, Kitchen Prep සහ Cashier Bill Settlement දක්වා සම්පූර්ණ ක්‍රියාවලිය.',
    category: 'orders',
    keywords: ['order flow', 'lifecycle', 'order status', 'confirmed', 'preparing', 'completed'],
    popular: true,
    contextRoutes: ['/dashboard/orders'],
    estimatedReadMinutes: 4,
    steps: [
      {
        number: 1,
        title: 'Customer Submits Order (Pending Approval or Confirmed)',
        titleSiEn: 'පාරිභෝගිකයා Order එක Submit කරයි',
        instruction: 'Customer scans the Table QR code and clicks Checkout. If Waiter Approval is enabled, the order waits in pending_waiter_approval status (hidden from Kitchen). If disabled, it confirms immediately.',
        instructionSiEn: 'පාරිභෝගිකයා Table QR එක scan කර Checkout click කරයි. Waiter Approval සක්‍රිය නම් Kitchen එකට නොපෙන්වා pending_waiter_approval තත්ත්වයේ තබයි. අක්‍රිය නම් කෙලින්ම Confirmed වේ.',
      },
      {
        number: 2,
        title: 'Waiter Approval → CONFIRMED',
        titleSiEn: 'Waiter Approval → CONFIRMED',
        instruction: 'If Waiter Approval is ON, waitstaff review the order on /dashboard/waiter and click "Approve Order". The order transitions to CONFIRMED and routes to the kitchen.',
        instructionSiEn: 'Waiter Approval ON නම් Waiter Terminal (/dashboard/waiter) වෙතින් "Approve Order" click කළ පසු order එක CONFIRMED වී Kitchen එකට යොමුවේ.',
      },
      {
        number: 3,
        title: 'Kitchen Ticket (PREPARING → READY)',
        titleSiEn: 'Kitchen Ticket එක (PREPARING → READY)',
        instruction: 'Kitchen staff view the ticket in Kitchen Queue (/dashboard/kitchen), click "🍳 Start Preparing" (PREPARING), and click "🔔 Mark Ready to Serve" (READY) when cooked.',
        instructionSiEn: 'Kitchen Queue (/dashboard/kitchen) හි ticket එක දිස්වේ. පිසීම ආරම්භයේදී "🍳 Start Preparing" සහ අවසන් වූ විට "🔔 Mark Ready to Serve" click කරයි.',
      },
      {
        number: 4,
        title: 'Cashier POS Settlement (COMPLETED)',
        titleSiEn: 'Cashier POS Bill Settlement (COMPLETED)',
        instruction: 'Cashier opens Cashier POS (/dashboard/cashier), clicks "💳 Settle", selects payment method (Cash, Card, QR), and clicks "Confirm Payment" to complete the order.',
        instructionSiEn: 'Cashier POS (/dashboard/cashier) වෙතින් "💳 Settle" click කර payment method එක (Cash, Card, QR) තෝරා "Confirm Payment" මඟින් order එක සම්පූර්ණ (COMPLETED) කරයි.',
      },
    ],
    relatedArticles: ['waiter-approval-before-kitchen', 'kitchen-queue-kds-overview', 'cashier-pos-overview'],
    directAction: {
      label: 'Open Orders Queue',
      labelSiEn: 'Orders Queue වෙත යන්න',
      href: '/dashboard/orders',
    },
  },
  {
    slug: 'waiter-approval-before-kitchen',
    title: 'How Waiter Approval Before Kitchen Works',
    titleSiEn: 'Waiter Approval Before Kitchen ක්‍රියාත්මක වන ආකාරය',
    description: 'Learn how to verify guest table orders before firing tickets to the kitchen, preventing accidental or unauthorized orders.',
    descriptionSiEn: 'Kitchen එකට order එක යැවීමට පෙර Waiter කෙනෙකු විසින් තහවුරු කරගැනීමේ ආරක්ෂිත ක්‍රමවේදය.',
    category: 'orders',
    keywords: ['waiter approval', 'approval gate', 'order verification', 'prevent pranks'],
    contextRoutes: ['/dashboard/settings/order-security', '/dashboard/waiter'],
    estimatedReadMinutes: 3,
    steps: [
      {
        number: 1,
        title: 'Enable Policy in Order Security',
        titleSiEn: 'Order Security හි Policy එක සක්‍රිය කරන්න',
        instruction: 'Go to Settings → Order Security (/dashboard/settings/order-security). Enable "Waiter Approval Before Kitchen" or select Balanced/Strict preset.',
        instructionSiEn: 'Settings → Order Security (/dashboard/settings/order-security) වෙත ගොස් "Waiter Approval Before Kitchen" toggle එක ON කරන්න.',
      },
      {
        number: 2,
        title: 'Guest Places Order via QR',
        titleSiEn: 'පාරිභෝගිකයා QR හරහා Order එක දැමූ විට',
        instruction: 'The order appears on the Waiter Terminal (/dashboard/waiter) under "Pending QR Order Approvals". Kitchen and Cashier displays remain withheld.',
        instructionSiEn: 'Order එක Waiter Terminal (/dashboard/waiter) හි "Pending QR Order Approvals" යටතේ දිස්වේ. Waiter තහවුරු කරන තුරු Kitchen සහ Cashier වෙත නොපෙන්වයි.',
      },
      {
        number: 3,
        title: 'Waiter Reviews and Approves',
        titleSiEn: 'Waiter විසින් Review කර Approve කිරීම',
        instruction: 'The waiter checks with the table and clicks "Approve Order" (or "Reject" if invalid). The ticket immediately fires to the Kitchen Queue as CONFIRMED.',
        instructionSiEn: 'වේටර් මේසය පරීක්ෂා කර "Approve Order" click කරයි (හෝ අවලංගු නම් "Reject"). ක්ෂණිකව ticket එක CONFIRMED තත්ත්වයෙන් Kitchen Queue එකට යොමුවේ.',
      },
    ],
    relatedArticles: ['how-customer-orders-flow', 'order-security-overview'],
    directAction: {
      label: 'Configure Order Security',
      labelSiEn: 'Order Security සැකසීම',
      href: '/dashboard/settings/order-security',
    },
  },
  {
    slug: 'guest-assistance-calls',
    title: 'Handling Guest Assistance & Call Waiter Requests',
    titleSiEn: 'Guest Assistance සහ Call Waiter ඉල්ලීම් හැසිරවීම',
    description: 'How guests request assistance or the bill from their phone, and how waitstaff manage requests on the Waiter Terminal.',
    descriptionSiEn: 'පාරිභෝගිකයා තම දුරකථනයෙන් "Call Waiter" හෝ "Need Bill" දැමූ විට Waiter Terminal එකෙන් ඒවා කළමනාකරණය කරන ආකාරය.',
    category: 'orders',
    keywords: ['call waiter', 'guest assistance', 'water request', 'bill request', 'service calls'],
    contextRoutes: ['/dashboard/waiter'],
    estimatedReadMinutes: 2,
    steps: [
      {
        number: 1,
        title: 'Guest Taps Assistance Button on Mobile Menu',
        titleSiEn: 'පාරිභෝගිකයා Mobile Menu එකෙන් Assistance ඉල්ලීමක් කරයි',
        instruction: 'From the QR order tracker (/m/[token]), the customer taps "Call Waiter", "Need Water", "Need Bill", or "Need Assistance".',
        instructionSiEn: 'QR order tracker (/m/[token]) එකෙන් පාරිභෝගිකයා "Call Waiter", "Need Water", "Need Bill", හෝ "Need Assistance" click කරයි.',
      },
      {
        number: 2,
        title: 'Active Assistance Calls on Waiter Terminal',
        titleSiEn: 'Waiter Terminal එකේ Active Assistance Calls බැලීම',
        instruction: 'The request appears under "Active Assistance Calls" on /dashboard/waiter with status PENDING, showing the table name and call type.',
        instructionSiEn: 'Waiter Terminal (/dashboard/waiter) හි "Active Assistance Calls" යටතේ අදාළ Table නම සහ ඉල්ලීම් වර්ගය PENDING තත්ත්වයෙන් දිස්වේ.',
      },
      {
        number: 3,
        title: 'Accept and Complete Request',
        titleSiEn: 'ඉල්ලීම භාරගෙන සම්පූර්ණ කිරීම',
        instruction: 'Waitstaff tap "Accept Request ⚡" to claim the call (ACCEPTED), attend to the guest at their table, and tap "Mark Completed ✓" when finished.',
        instructionSiEn: 'Waitstaff විසින් "Accept Request ⚡" click කර ඉල්ලීම භාරගෙන (ACCEPTED), මේසයට සේවය සැපයූ පසු "Mark Completed ✓" click කර අවසන් කරයි.',
      },
    ],
    relatedArticles: ['waiter-terminal-overview', 'how-customer-orders-flow'],
    directAction: {
      label: 'Open Waiter Terminal',
      labelSiEn: 'Waiter Terminal වෙත යන්න',
      href: '/dashboard/waiter',
    },
  },
];

