import { HelpArticle } from '../types';

export const SERVICE_AREAS_TABLES_QR_ARTICLES: HelpArticle[] = [
  {
    slug: 'create-service-areas',
    title: 'How to Create and Manage Service Areas',
    titleSiEn: 'Service Areas නිර්මාණය සහ කළමනාකරණය කරන්නේ කෙසේද?',
    description: 'Organize your floor plan into zones like Main Dining Hall, Rooftop Bar, Patio Terrace, and VIP Lounge.',
    descriptionSiEn: 'Main Dining Hall, Rooftop Bar, Patio Terrace වැනි කලාප අනුව floor plan එක සකස් කරගන්නා ආකාරය.',
    category: 'service-areas-tables-qr',
    keywords: ['service areas', 'zones', 'floor plan', 'sections', 'rooftop', 'patio'],
    popular: true,
    contextRoutes: ['/dashboard/areas', '/dashboard/dining'],
    estimatedReadMinutes: 3,
    steps: [
      {
        number: 1,
        title: 'Navigate to Service Areas',
        titleSiEn: 'Service Areas වෙත යන්න',
        instruction: 'From the dashboard sidebar, click Dining & QR → Service Areas (/dashboard/areas).',
        instructionSiEn: 'Dashboard sidebar එකෙන් Dining & QR → Service Areas (/dashboard/areas) වෙත යන්න.',
      },
      {
        number: 2,
        title: 'Create an Area',
        titleSiEn: 'Service Area එකක් create කරන්න',
        instruction: 'Click "+ Add Service Area". Enter the Area Name (e.g. "Main Dining Room" or "Garden Terrace") and optional description.',
        instructionSiEn: '+ Add Service Area button එක click කරන්න. Area Name එක (උදා. "Main Dining Room" හෝ "Garden Terrace") ඇතුළත් කරන්න.',
      },
      {
        number: 3,
        title: 'Save and Add Tables',
        titleSiEn: 'Save කර Tables එක් කරන්න',
        instruction: 'Click "Create Area". Once created, you can begin adding tables inside this service area.',
        instructionSiEn: 'Create Area click කර save කරන්න. ඉන්පසු මෙම area එකට අදාළව Tables add කිරීම ආරම්භ කළ හැක.',
      },
    ],
    notes: [
      'You must have at least one active Service Area before you can add Dining Tables.',
    ],
    notesSiEn: [
      'Dining Tables එකතු කිරීමට පෙර අවම වශයෙන් එක් Service Area එකක් හෝ create කර තිබිය යුතුය.',
    ],
    relatedArticles: ['add-dining-tables', 'generating-and-printing-qr-codes', 'configure-table-pins'],

    directAction: {
      label: 'Open Service Areas',
      labelSiEn: 'Service Areas වෙත යන්න',
      href: '/dashboard/areas',
    },
  },
  {
    slug: 'add-dining-tables',
    title: 'How to Add and Manage Dining Tables',
    titleSiEn: 'Dining Tables එකතු කිරීම සහ කළමනාකරණය කරන්නේ කෙසේද?',
    description: 'Add individual dining tables, set guest seating capacities, assign to service areas, and configure table numbers.',
    descriptionSiEn: 'Service Area වලට අදාළව මේස අංක, ආසන ධාරිතාව (capacity) සහිතව Tables එකතු කරන ආකාරය.',
    category: 'service-areas-tables-qr',
    keywords: ['tables', 'dining tables', 'add table', 'table numbers', 'seating capacity'],
    popular: true,
    contextRoutes: ['/dashboard/tables', '/dashboard/tables/new', '/dashboard/tables/bulk'],
    estimatedReadMinutes: 3,
    steps: [
      {
        number: 1,
        title: 'Go to Dining Tables',
        titleSiEn: 'Dining Tables වෙත යන්න',
        instruction: 'Navigate to Dining & QR → Dining Tables (/dashboard/tables).',
        instructionSiEn: 'Dining & QR → Dining Tables (/dashboard/tables) වෙත යන්න.',
      },
      {
        number: 2,
        title: 'Add a Table',
        titleSiEn: 'Add Table click කරන්න',
        instruction: 'Click "+ Add Table" (or "Bulk Table Setup" for multiple tables). Select the Service Area, enter Table Number (e.g. "T-01"), and Guest Capacity.',
        instructionSiEn: '+ Add Table button එක click කරන්න. Service Area එක තෝරා Table Number (උදා. "T-01") සහ Seating Capacity ඇතුළත් කරන්න.',
      },
      {
        number: 3,
        title: 'Save Table',
        titleSiEn: 'Save කර Table එක එක් කරන්න',
        instruction: 'Click "Create Table". Your table is now saved and will appear on the floor layout and waiter terminal.',
        instructionSiEn: '"Create Table" click කරන්න. දැන් මෙම table එක floor layout සහ waiter terminal වල දිස්වනු ඇත.',
      },
    ],
    relatedArticles: ['create-service-areas', 'generating-and-printing-qr-codes', 'configure-table-pins'],
    directAction: {
      label: 'Manage Dining Tables',
      labelSiEn: 'Dining Tables කළමනාකරණය',
      href: '/dashboard/tables',
    },
  },
  {
    slug: 'generating-and-printing-qr-codes',
    title: 'How to Generate and Download Branch QR Codes',
    titleSiEn: 'Branch QR Codes generate කිරීම සහ download කරන්නේ කෙසේද?',
    description: 'Generate encrypted QR codes for public branch menus, print table cards, and test camera scanning.',
    descriptionSiEn: 'Branch එක සඳහා encrypted QR codes generate කිරීම, Print කර මේස මත තැබීම සහ mobile phone මඟින් scan කර බැලීම.',
    category: 'service-areas-tables-qr',
    keywords: ['qr code', 'qr codes', 'generate qr', 'table qr', 'print qr', 'scan menu', 'branch qr'],
    popular: true,
    contextRoutes: ['/dashboard/tables/qr'],
    estimatedReadMinutes: 4,
    steps: [
      {
        number: 1,
        title: 'Navigate to QR Codes',
        titleSiEn: 'QR Codes කළමනාකරණයට යන්න',
        instruction: 'Go to Dining & QR → QR Codes (/dashboard/tables/qr).',
        instructionSiEn: 'Dining & QR → QR Codes (/dashboard/tables/qr) වෙත යන්න.',
      },
      {
        number: 2,
        title: 'Generate Branch QR Code',
        titleSiEn: 'Branch QR Code එක Generate කරන්න',
        instruction: 'If your branch does not have an active QR code, click "✨ Generate Branch QR Code". WSNexa creates a cryptographically secure token.',
        instructionSiEn: 'ඔබගේ branch එකට active QR එකක් නොමැති නම් "✨ Generate Branch QR Code" click කරන්න. පද්ධතිය මඟින් ආරක්ෂිත QR token එකක් සකස් කරනු ඇත.',
      },
      {
        number: 3,
        title: 'Download PNG or Print QR Card',
        titleSiEn: 'Download කර Print කරන්න',
        instruction: 'Click "💾 Download High-Res PNG" or "🖨️ Print Branch QR Card" to prepare physical table stands for your dining area.',
        instructionSiEn: '"💾 Download High-Res PNG" හෝ "🖨️ Print Branch QR Card" click කර dining tables මත තැබීමට QR කාඩ්පත් මුද්‍රණය කරගන්න.',
      },
    ],
    notes: [
      'Customer scans route securely to /m/[token] without requiring customers to install any mobile app.',
    ],
    notesSiEn: [
      'පාරිභෝගිකයින්ට කිසිදු app එකක් අවශ්‍ය නොවන අතර smartphone camera එකෙන් scan කළ සැනින් /m/[token] ඔස්සේ digital menu එක open වේ.',
    ],
    relatedArticles: ['configure-table-pins', 'how-customers-use-qr-ordering', 'customer-cannot-open-qr-menu'],
    directAction: {
      label: 'Open QR Codes',
      labelSiEn: 'QR Codes වෙත යන්න',
      href: '/dashboard/tables/qr',
    },
  },
  {
    slug: 'configure-table-pins',
    title: 'How to Configure and Manage Table PINs',
    titleSiEn: 'Table PINs configure කරන්නේ කෙසේද?',
    description: 'Protect physical table orders from remote fake orders by requiring a 4-6 digit PIN displayed only on the physical table tent.',
    descriptionSiEn: 'මේසය මත ඇති 4-6 digit Table PIN එක ඇතුළත් කිරීම අනිවාර්ය කර දුරස්ථව සිදුවන ව්‍යාජ orders වැළැක්වීම.',
    category: 'service-areas-tables-qr',
    keywords: ['table pin', 'pin protection', 'anti-fraud', 'security pin', 'table tent'],
    contextRoutes: ['/dashboard/tables/qr', '/dashboard/settings/order-security'],
    estimatedReadMinutes: 3,
    steps: [
      {
        number: 1,
        title: 'Enable Table PIN Setting',
        titleSiEn: 'Table PIN සැකසුම සක්‍රිය කරන්න',
        instruction: 'On /dashboard/tables/qr (or Settings → Order Security), toggle "Require Table PIN" to ON.',
        instructionSiEn: '/dashboard/tables/qr හි (හෝ Settings → Order Security හි) "Require Table PIN" toggle එක ON කරන්න.',
      },
      {
        number: 2,
        title: 'Generate Table PINs',
        titleSiEn: 'Table PINs සකසන්න',
        instruction: 'Under Table PIN Readiness on /dashboard/tables/qr, click "⚡ Bulk Generate Missing PINs" to assign PINs across all branch tables.',
        instructionSiEn: '/dashboard/tables/qr හි "⚡ Bulk Generate Missing PINs" click කර සියලුම tables සඳහා PIN අංක ලබාදෙන්න.',
      },
      {
        number: 3,
        title: 'Display PINs on Physical Table Stands',
        titleSiEn: 'Table Stands මත PIN අංකය සටහන් කරන්න',
        instruction: 'Ensure the table tent card or printed QR stand clearly displays the table\'s specific PIN for dining guests.',
        instructionSiEn: 'අදාළ මේසය මත තබන QR card එකෙහි මෙම PIN අංකය පාරිභෝගිකයාට දැකගත හැකි වන සේ පැහැදිලිව සඳහන් කර තබන්න.',
      },
    ],
    notes: [
      'If Require Table PIN is disabled, customers can order directly after scanning the QR code.',
    ],
    notesSiEn: [
      'Require Table PIN අක්‍රිය කර ඇත්නම් පාරිභෝගිකයාට PIN එකක් නොමැතිව කෙලින්ම order කළ හැක.',
    ],
    relatedArticles: ['generating-and-printing-qr-codes', 'order-security-overview', 'table-pin-not-working'],
    directAction: {
      label: 'Configure Table PINs',
      labelSiEn: 'Table PINs සැකසීම',
      href: '/dashboard/tables/qr',
    },
  },

  {
    slug: 'how-customers-use-qr-ordering',
    title: 'How Customers Experience QR Ordering',
    titleSiEn: 'පාරිභෝගිකයින් QR මෙනුව භාවිතා කර ඇණවුම් කරන ආකාරය',
    description: 'Learn the customer journey: scanning the QR code, browsing categories, adding modifiers, and submitting orders.',
    descriptionSiEn: 'පාරිභෝගිකයෙකු QR code එක scan කිරීම, කෑම තේරීම, Modifiers එකතු කිරීම සහ order එක submit කිරීමේ පියවර.',
    category: 'service-areas-tables-qr',
    keywords: ['customer experience', 'qr ordering', 'guest ordering', 'scan and order'],
    estimatedReadMinutes: 3,
    steps: [
      {
        number: 1,
        title: 'Scan QR with Phone Camera',
        titleSiEn: 'Smartphone Camera එකෙන් Scan කිරීම',
        instruction: 'The guest opens their default phone camera or Google Lens and taps the QR banner to open the digital menu at /m/[token].',
        instructionSiEn: 'පාරිභෝගිකයා තමන්ගේ smartphone camera එකෙන් table QR code එක scan කළ විට ඩිජිටල් මෙනුව (/m/[token]) open වේ.',
      },
      {
        number: 2,
        title: 'Browse Menu & Customize',
        titleSiEn: 'කෑම තෝරා Customize කිරීම',
        instruction: 'Guests select items, choose modifier options (e.g. Spice Level, Portion Size), and add to cart.',
        instructionSiEn: 'කෑම සහ බීම වර්ග තෝරා, අවශ්‍ය නම් Modifiers (උදා. Spice Level, Large/Regular) තෝරා Cart එකට එකතු කරයි.',
      },
      {
        number: 3,
        title: 'Submit Order',
        titleSiEn: 'Order එක Submit කිරීම',
        instruction: 'Guest clicks Checkout, enters Table PIN if required, and submits. The order instantly routes to Waiters or Kitchen.',
        instructionSiEn: 'Checkout click කර Table PIN එක (අවශ්‍ය නම්) ලබාදී order එක submit කරයි. ක්ෂණිකව Waiters හෝ Kitchen වෙත order එක යොමුවේ.',
      },
    ],
    relatedArticles: ['generating-and-printing-qr-codes', 'how-customer-orders-flow'],

    directAction: {
      label: 'View Dining & QR',
      labelSiEn: 'Dining & QR බලන්න',
      href: '/dashboard/dining',
    },
  },
];
