import { HelpArticle } from '../types';

export const STAFF_ROLES_PERMISSIONS_ARTICLES: HelpArticle[] = [
  {
    slug: 'invite-staff-members',
    title: 'How to Invite Staff Members and Assign Roles',
    titleSiEn: 'Staff සාමාජිකයින් Invite කර Roles ලබාදෙන්නේ කෙසේද?',
    description: 'Invite managers, cashiers, chefs, and waitstaff using email invitations or instant claim links.',
    descriptionSiEn: 'Managers, Cashiers, Chefs සහ Waiters පද්ධතියට එක් කරගැනීම සඳහා Invite Links යවන ආකාරය.',
    category: 'staff-roles-permissions',
    keywords: ['invite staff', 'add employee', 'claim link', 'team member', 'invitations'],
    popular: true,
    contextRoutes: ['/dashboard/team/invites', '/dashboard/team'],
    estimatedReadMinutes: 3,
    steps: [
      {
        number: 1,
        title: 'Navigate to Staff Invitations',
        titleSiEn: 'Staff Invitations වෙත යන්න',
        instruction: 'From the dashboard sidebar, navigate to Team → Staff Invitations (/dashboard/team/invites).',
        instructionSiEn: 'Dashboard sidebar එකෙන් Team → Staff Invitations (/dashboard/team/invites) වෙත යන්න.',
      },
      {
        number: 2,
        title: 'Create an Invitation',
        titleSiEn: 'Invitation එකක් create කරන්න',
        instruction: 'Click "+ Invite Staff Member". Enter the staff email (or username) and select their role (e.g. "Cashier", "Kitchen Staff", "Waiter").',
        instructionSiEn: '+ Invite Staff Member click කරන්න. Email ලිපිනය සහ Role එක (උදා. "Cashier", "Kitchen Staff", "Waiter") තෝරන්න.',
      },
      {
        number: 3,
        title: 'Copy and Share Claim Link',
        titleSiEn: 'Claim Link එක Share කරන්න',
        instruction: 'Click "Send Invitation" and copy the unique claim link to share with your staff member over WhatsApp or SMS.',
        instructionSiEn: 'Send Invitation click කර Claim Link එක copy කර අදාළ සේවකයාට WhatsApp හෝ SMS මඟින් යවන්න.',
      },
    ],
    relatedArticles: ['roles-and-permissions-guide', 'branch-and-area-scopes'],
    directAction: {
      label: 'Invite Staff',
      labelSiEn: 'Staff Invite කරන්න',
      href: '/dashboard/team/invites',
    },
  },
  {
    slug: 'roles-and-permissions-guide',
    title: 'Understanding Built-in Roles & Custom Permissions',
    titleSiEn: 'Built-in Roles සහ Custom Permissions තේරුම් ගැනීම',
    description: 'Learn the exact capability bundles for Business Owners, Branch Managers, Cashiers, Kitchen Staff, and Waiters.',
    descriptionSiEn: 'Business Owner, Manager, Cashier, Kitchen Staff සහ Waiter යන භූමිකාවන්ට හිමිවන බලතල සහ අවසර.',
    category: 'staff-roles-permissions',
    keywords: ['roles', 'permissions', 'rbac', 'cashier role', 'waiter role', 'kitchen role'],
    contextRoutes: ['/dashboard/access/roles'],
    estimatedReadMinutes: 4,
    steps: [
      {
        number: 1,
        title: 'Review Built-in Role Templates',
        titleSiEn: 'Built-in Role Templates පරීක්ෂා කරන්න',
        instruction: 'WSNexa provides 5 canonical roles: Business Owner (full access), Branch Manager (operations & staff), Cashier (POS & billing), Kitchen (prep queues), Waiter (table ordering & alerts).',
        instructionSiEn: 'WSNexa හි ප්‍රධාන roles 5 කි: Business Owner (සම්පූර්ණ පාලනය), Branch Manager, Cashier (බිල්පත්), Kitchen (කෑම පිසීම), Waiter (මේස ඇණවුම්).',
      },
      {
        number: 2,
        title: 'Create Custom Roles (Optional)',
        titleSiEn: 'Custom Roles සාදන්න (විකල්ප)',
        instruction: 'Go to Team → Roles & Permissions (/dashboard/access/roles) to create tailored roles like "Head Chef" or "Senior Supervisor".',
        instructionSiEn: 'Team → Roles & Permissions (/dashboard/access/roles) වෙත ගොස් "Head Chef" හෝ "Supervisor" වැනි විශේෂ roles සෑදිය හැක.',
      },
    ],
    relatedArticles: ['invite-staff-members', 'branch-and-area-scopes'],
    directAction: {
      label: 'View Roles & Permissions',
      labelSiEn: 'Roles & Permissions බලන්න',
      href: '/dashboard/access/roles',
    },
  },
  {
    slug: 'branch-and-area-scopes',
    title: 'Assigning Branch and Service Area Scopes to Staff',
    titleSiEn: 'Staff සාමාජිකයින්ට Branch සහ Service Area Scopes ලබාදීම',
    description: 'Restrict staff access so waiters only see their assigned branch and designated service areas.',
    descriptionSiEn: 'සේවකයින්ට තමන්ට අදාළ ශාඛාව සහ Service Areas පමණක් පෙනෙන පරිදි සීමා පැනවීම.',
    category: 'staff-roles-permissions',
    keywords: ['scopes', 'branch scope', 'area scope', 'scope grants', 'staff restrictions'],
    contextRoutes: ['/dashboard/access/scope-grants', '/dashboard/team'],
    estimatedReadMinutes: 3,
    steps: [
      {
        number: 1,
        title: 'Open Scope Grants',
        titleSiEn: 'Scope Grants වෙත යන්න',
        instruction: 'Go to Team → Scope Grants (/dashboard/access/scope-grants).',
        instructionSiEn: 'Team → Scope Grants (/dashboard/access/scope-grants) වෙත යන්න.',
      },
      {
        number: 2,
        title: 'Select Staff Member and Assign Scope',
        titleSiEn: 'සේවකයා තෝරා Scope එකක් ලබාදෙන්න',
        instruction: 'Assign the staff member to specific Branch Outlets (e.g. "Colombo Branch") or Service Areas (e.g. "Rooftop Only").',
        instructionSiEn: 'අදාළ සේවකයාට හිමි Branch එක හෝ Service Area එක (උදා. "Rooftop Only") තෝරා assign කරන්න.',
      },
    ],
    relatedArticles: ['invite-staff-members', 'roles-and-permissions-guide'],
    directAction: {
      label: 'Manage Scope Grants',
      labelSiEn: 'Scope Grants කළමනාකරණය',
      href: '/dashboard/access/scope-grants',
    },
  },
  {
    slug: 'organization-structure-positions',
    title: 'Organization Structure, Positions & Job Titles',
    titleSiEn: 'Organization Structure, Positions සහ Job Titles සැකසීම',
    description: 'Structure multi-level enterprise teams, manage job titles, and view the visual organization chart.',
    descriptionSiEn: 'විශාල ව්‍යාපාර සඳහා ආයතනික ධුරාවලිය, තනතුරු නාම සහ Org Chart සකස් කරගැනීම.',
    category: 'staff-roles-permissions',
    keywords: ['organization', 'positions', 'job titles', 'org chart', 'structure'],
    contextRoutes: ['/dashboard/organization', '/dashboard/organization/chart'],
    estimatedReadMinutes: 3,
    steps: [
      {
        number: 1,
        title: 'Explore Organization Structure',
        titleSiEn: 'Organization Structure බලන්න',
        instruction: 'Go to Team → Org Structure (/dashboard/organization/structure) to manage departments and positions.',
        instructionSiEn: 'Team → Org Structure (/dashboard/organization/structure) වෙත ගොස් departments සහ positions සකසන්න.',
      },
      {
        number: 2,
        title: 'View Organization Chart',
        titleSiEn: 'Organization Chart එක බලන්න',
        instruction: 'View the live interactive Org Chart at /dashboard/organization/chart.',
        instructionSiEn: '/dashboard/organization/chart හි ඇති visual Org Chart එක පරීක්ෂා කරන්න.',
      },
    ],
    relatedArticles: ['roles-and-permissions-guide', 'invite-staff-members'],
    directAction: {
      label: 'View Org Structure',
      labelSiEn: 'Org Structure බලන්න',
      href: '/dashboard/organization',
    },
  },
];
