import { HelpArticle } from '../types';

export const TROUBLESHOOTING_ARTICLES: HelpArticle[] = [
  {
    slug: 'customer-cannot-open-qr-menu',
    title: 'Troubleshooting: Customer Cannot Open QR Menu',
    titleSiEn: 'ගැටළු විසඳීම: පාරිභෝගිකයාට QR Menu එක open කරගත නොහැකි වූ විට',
    description: 'Practical steps to diagnose expired QR tokens, missing internet connection, or inactive branch QR codes.',
    descriptionSiEn: 'QR code එක scan කළ විට menu එක load නොවීමට හේතු සහ විසඳුම්.',
    category: 'troubleshooting',
    keywords: ['qr error', 'cannot scan', 'invalid qr', 'qr expired', 'camera issue'],
    troubleshooting: true,
    popular: true,
    estimatedReadMinutes: 3,
    steps: [
      {
        number: 1,
        title: 'Check Branch QR Code Activation',
        titleSiEn: 'Branch QR Code එක Active දැයි පරීක්ෂා කරන්න',
        instruction: 'Go to Dining & QR → QR Codes (/dashboard/tables/qr). Ensure an active QR token is generated. If none exists or if it was revoked, click "✨ Generate Branch QR Code".',
        instructionSiEn: 'Dining & QR → QR Codes (/dashboard/tables/qr) වෙත යන්න. Active QR එකක් තිබේදැයි බලන්න. නැතිනම් "✨ Generate Branch QR Code" click කරන්න.',
      },

      {
        number: 2,
        title: 'Verify Customer Internet Connection',
        titleSiEn: 'පාරිභෝගිකයාගේ Internet සම්බන්ධතාවය පරීක්ෂා කරන්න',
        instruction: 'Ensure the customer\'s mobile device is connected to Mobile Data or your restaurant\'s Guest Wi-Fi.',
        instructionSiEn: 'පාරිභෝගිකයාගේ phone එක Mobile Data හෝ Restaurant Guest Wi-Fi සමඟ සම්බන්ධ වී ඇත්දැයි බලන්න.',
      },
      {
        number: 3,
        title: 'Check Published Menu Items',
        titleSiEn: 'Active Menu Items තිබේදැයි බලන්න',
        instruction: 'Ensure at least one Menu Category and active Menu Item exist; otherwise the public menu displays an empty venue notice.',
        instructionSiEn: 'අවම වශයෙන් එක් Category එකක් සහ Active Menu Item එකක් හෝ තිබිය යුතුය.',
      },
    ],
    troubleshootingChecks: [
      {
        check: 'Does the scanner show "INVALID_QR"?',
        checkSiEn: 'Screen එකේ "INVALID_QR" ලෙස පෙන්වයිද?',
        action: 'Re-generate the Branch QR Code from Dining & QR → QR Codes and reprint table cards.',
        actionSiEn: 'Dining & QR → QR Codes වෙත ගොස් Generate Branch QR click කර අලුතින් Print කරන්න.',
      },
      {
        check: 'Is the restaurant branch marked Inactive?',
        checkSiEn: 'Branch එක Inactive වී තිබේද?',
        action: 'Go to Settings → Branch Outlets and verify the branch active toggle is ON.',
        actionSiEn: 'Settings → Branch Outlets වෙත ගොස් branch active switch එක ON දැයි බලන්න.',
      },
    ],
    relatedArticles: ['generating-and-printing-qr-codes', 'table-pin-not-working'],

    directAction: {
      label: 'Open QR Codes',
      labelSiEn: 'QR Codes වෙත යන්න',
      href: '/dashboard/tables/qr',
    },
  },
  {
    slug: 'table-pin-not-working',
    title: 'Troubleshooting: Table PIN Error / Not Working',
    titleSiEn: 'ගැටළු විසඳීම: Table PIN එක වැරදි බව හෝ ක්‍රියා නොකරන විට',
    description: 'Resolve guest checkout PIN mismatches, verify assigned table PINs, or temporarily disable PIN enforcement.',
    descriptionSiEn: 'පාරිභෝගිකයා Table PIN එක ඇතුළත් කළ විට Invalid PIN වැටීමට හේතු සහ විසඳුම්.',
    category: 'troubleshooting',
    keywords: ['pin error', 'invalid pin', 'table pin incorrect', 'bypass pin'],
    troubleshooting: true,
    popular: true,
    estimatedReadMinutes: 3,
    steps: [
      {
        number: 1,
        title: 'Inspect Table PIN Configuration',
        titleSiEn: 'Table PIN එක පරීක්ෂා කරන්න',
        instruction: 'Go to Dining & QR → QR Codes (/dashboard/tables/qr). Verify the exact 4-digit PIN assigned to the table number.',
        instructionSiEn: 'Dining & QR → QR Codes (/dashboard/tables/qr) වෙත ගොස් අදාළ table එකට ලබාදී ඇති 4-digit PIN අංකය බලන්න.',
      },
      {
        number: 2,
        title: 'Ensure Printed Card Matches System PIN',
        titleSiEn: 'මේසය මත ඇති Card එක සමඟ සංසන්දනය කරන්න',
        instruction: 'Check if the physical table card on the table displays the exact same number configured in WSNexa.',
        instructionSiEn: 'මේසය මත තබා ඇති කාඩ්පතෙහි ඇති අංකය සහ පද්ධතියේ ඇති අංකය සමාන දැයි තහවුරු කරගන්න.',
      },
      {
        number: 3,
        title: 'Toggle PIN Requirement If Needed',
        titleSiEn: 'අවශ්‍ය නම් PIN Requirement එක తాත්කාලිකව Disable කරන්න',
        instruction: 'If you want to allow orders without PINs, go to Settings → Order Security and toggle "Require Table PIN" OFF.',
        instructionSiEn: 'PIN එකක් නොමැතිව orders ගැනීමට අවශ්‍ය නම් Settings → Order Security වෙත ගොස් "Require Table PIN" switch එක OFF කරන්න.',
      },
    ],
    relatedArticles: ['configure-table-pins', 'order-security-overview'],
    directAction: {
      label: 'Manage Table PINs',
      labelSiEn: 'Table PINs කළමනාකරණය',
      href: '/dashboard/tables/qr',
    },
  },
  {
    slug: 'troubleshooting-order-not-reaching-kitchen',
    title: 'Troubleshooting: Order Not Appearing in Kitchen Queue',
    titleSiEn: 'ගැටළු විසඳීම: Order එක Kitchen Queue එකේ නොපෙන්වන විට',
    description: 'Diagnose why a submitted customer order has not appeared on the Kitchen KDS screen.',
    descriptionSiEn: 'පාරිභෝගිකයා order එක දැමූ නමුත් Kitchen screen එකෙහි ticket එක නොපෙන්වීමට හේතු.',
    category: 'troubleshooting',
    keywords: ['order not reaching kitchen', 'kitchen missing', 'order not in kitchen', 'kds missing', 'waiter approval pending'],

    troubleshooting: true,
    popular: true,
    estimatedReadMinutes: 3,
    steps: [
      {
        number: 1,
        title: 'Check If Order Is Awaiting Waiter Approval',
        titleSiEn: 'Order එක Waiter Approval බලාපොරොත්තුවෙන් ඇත්දැයි බලන්න',
        instruction: 'If "Waiter Approval Before Kitchen" is enabled in Order Security, the order will NOT appear in the kitchen until a waiter approves it on /dashboard/waiter.',
        instructionSiEn: 'Order Security හි "Waiter Approval Before Kitchen" ON නම්, වේටර්වරයෙකු /dashboard/waiter මඟින් approve කරන තුරු Kitchen එකට ticket එක නොයයි.',
      },
      {
        number: 2,
        title: 'Check Branch Isolation Context',
        titleSiEn: 'Kitchen screen එකේ Branch එක පරීක්ෂා කරන්න',
        instruction: 'Ensure the kitchen tablet is logged into the same branch outlet where the customer placed the table order.',
        instructionSiEn: 'Kitchen tablet එකෙහි තෝරා ඇති Branch එක සහ පාරිභෝගිකයා order කළ Branch එක සමාන දැයි බලන්න.',
      },
      {
        number: 3,
        title: 'Inspect Live Orders Queue',
        titleSiEn: 'Orders Queue එක පරීක්ෂා කරන්න',
        instruction: 'Go to Orders → Orders Queue (/dashboard/orders) to inspect the order status and check if it was cancelled or rejected.',
        instructionSiEn: 'Orders → Orders Queue (/dashboard/orders) වෙත ගොස් order එකෙහි status එක Confirmed ද නැතහොත් Cancelled දැයි බලන්න.',
      },
    ],
    relatedArticles: ['waiter-approval-before-kitchen', 'kitchen-queue-kds-overview'],
    directAction: {
      label: 'Open Kitchen Queue',
      labelSiEn: 'Kitchen Queue වෙත යන්න',
      href: '/dashboard/kitchen',
    },
  },
  {
    slug: 'order-not-appearing-in-cashier',
    title: 'Troubleshooting: Order Not Appearing in Cashier POS',
    titleSiEn: 'ගැටළු විසඳීම: Order එක Cashier POS එකෙහි නොපෙන්වන විට',
    description: 'Diagnose unsettled table bills, cancelled tickets, or filter mismatches in Cashier POS.',
    descriptionSiEn: 'බිල්පතක් Cashier POS හි නොපෙන්වීමට හේතු සහ විසඳුම්.',
    category: 'troubleshooting',
    keywords: ['cashier missing', 'bill missing', 'cannot settle', 'pos error'],
    troubleshooting: true,
    estimatedReadMinutes: 2,
    steps: [
      {
        number: 1,
        title: 'Check Table Filter in Cashier',
        titleSiEn: 'Cashier POS හි Table Filter එක බලන්න',
        instruction: 'On /dashboard/cashier, ensure you have selected the correct Service Area tab or "All Tables".',
        instructionSiEn: '/dashboard/cashier හි අදාළ Service Area tab එක හෝ "All Tables" තෝරා ඇති බව තහවුරු කරන්න.',
      },
      {
        number: 2,
        title: 'Verify Order Status in Orders Hub',
        titleSiEn: 'Orders Hub හි Status එක බලන්න',
        instruction: 'If the order was already completed or marked cancelled, it moves from the active cashier queue to order history.',
        instructionSiEn: 'Order එක කලින්ම Complete හෝ Cancel කර ඇත්නම් එය Cashier Active Queue එකෙන් ඉවත් වේ.',
      },
    ],
    relatedArticles: ['cashier-pos-overview', 'settling-table-bills'],
    directAction: {
      label: 'Open Cashier POS',
      labelSiEn: 'Cashier POS වෙත යන්න',
      href: '/dashboard/cashier',
    },
  },
  {
    slug: 'staff-cannot-access-page',
    title: 'Troubleshooting: Staff Member Cannot Access a Page (403 Forbidden)',
    titleSiEn: 'ගැටළු විසඳීම: සේවකයෙකුට පිටුවක් open කළ නොහැකි වූ විට (Access Denied)',
    description: 'Resolve permission denied errors, missing scope grants, or incorrect role assignments.',
    descriptionSiEn: 'සේවකයෙකුට Access Denied (403) පණිවිඩයක් ලැබෙන විට විසඳන ආකාරය.',
    category: 'troubleshooting',
    keywords: ['access denied', '403 forbidden', 'permission error', 'staff locked out', 'scope error'],
    troubleshooting: true,
    estimatedReadMinutes: 3,
    steps: [
      {
        number: 1,
        title: 'Verify Staff Assigned Role',
        titleSiEn: 'සේවකයාගේ Role එක පරීක්ෂා කරන්න',
        instruction: 'Go to Team → Staff Directory (/dashboard/team). Check the staff member\'s assigned role.',
        instructionSiEn: 'Team → Staff Directory (/dashboard/team) වෙත ගොස් අදාළ සේවකයාගේ Role එක බලන්න.',
      },
      {
        number: 2,
        title: 'Check Branch Scope Grants',
        titleSiEn: 'Branch Scope Grants පරීක්ෂා කරන්න',
        instruction: 'Go to Team → Scope Grants. If the staff member is restricted to Branch A, they cannot access Branch B data.',
        instructionSiEn: 'Team → Scope Grants වෙත ගොස් අදාළ සේවකයාට එම Branch එකට අවසර ලබාදී ඇත්දැයි බලන්න.',
      },
      {
        number: 3,
        title: 'Inspect Access Diagnostics',
        titleSiEn: 'Access Diagnostics මඟින් පරීක්ෂා කරන්න',
        instruction: 'Open Team → Access Diagnostics (/dashboard/access/diagnostics) to evaluate exact permission evaluations.',
        instructionSiEn: 'Team → Access Diagnostics (/dashboard/access/diagnostics) මඟින් සේවකයාගේ සියලුම permissions නිවැරදි දැයි බලන්න.',
      },
    ],
    relatedArticles: ['roles-and-permissions-guide', 'branch-and-area-scopes'],
    directAction: {
      label: 'Open Staff Directory',
      labelSiEn: 'Staff Directory වෙත යන්න',
      href: '/dashboard/team',
    },
  },
  {
    slug: 'payment-method-not-visible',
    title: 'Troubleshooting: Payment Method Not Visible at Checkout',
    titleSiEn: 'ගැටළු විසඳීම: Checkout හිදී Payment Method එක නොපෙන්වන විට',
    description: 'How to enable Cash or Card POS options in branch payment settings so customers and cashiers can select them.',
    descriptionSiEn: 'ගෙවීම් කිරීමට යාමේදී Payment Options නොපෙන්වීමට හේතු සහ විසඳුම්.',
    category: 'troubleshooting',
    keywords: ['payment missing', 'no payment methods', 'checkout payment error', 'enable payment'],
    troubleshooting: true,
    estimatedReadMinutes: 2,
    steps: [
      {
        number: 1,
        title: 'Open Branch Payment Settings',
        titleSiEn: 'Branch Payment Settings වෙත යන්න',
        instruction: 'Navigate to Settings → Payment Methods (/dashboard/settings/payments).',
        instructionSiEn: 'Settings → Payment Methods (/dashboard/settings/payments) වෙත යන්න.',
      },
      {
        number: 2,
        title: 'Turn ON At Least One Method',
        titleSiEn: 'අවම වශයෙන් එක් ක්‍රමයක් හෝ ON කරන්න',
        instruction: 'Toggle ON Cash, Terminal Card, or External QR, enter customer display titles, and click "Save Method Labels".',
        instructionSiEn: 'Cash, Terminal Card හෝ External QR switch එක ON කර, මාතෘකාව ඇතුළත් කර "Save Method Labels" click කරන්න.',
      },

    ],
    relatedArticles: ['configuring-payment-methods', 'payment-types-cash-card-online'],
    directAction: {
      label: 'Configure Payments',
      labelSiEn: 'Payments සැකසීම',
      href: '/dashboard/settings/payments',
    },
  },
  {
    slug: 'setup-progress-looks-incomplete',
    title: 'Troubleshooting: Guided Setup Progress Looks Incomplete',
    titleSiEn: 'ගැටළු විසඳීම: Setup Progress එක incomplete ලෙස පෙන්වන විට',
    description: 'Understand the exact criteria required for each stage: tables must have areas, QR codes must be active, and test orders must progress downstream.',
    descriptionSiEn: 'Setup එක 100% complete වීමට අවශ්‍ය නිවැරදි කොන්දේසි පරීක්ෂා කරගන්නා ආකාරය.',
    category: 'troubleshooting',
    keywords: ['setup incomplete', 'setup blocked', 'why is setup not complete', 'guided setup error'],
    troubleshooting: true,
    popular: true,
    estimatedReadMinutes: 3,
    steps: [
      {
        number: 1,
        title: 'Check Dining & QR Stage',
        titleSiEn: 'Dining & QR අදියර පරීක්ෂා කරන්න',
        instruction: 'Dining setup requires at least 1 Service Area, at least 1 Table, Table PINs configured (if PIN is required), AND an active Branch QR generated.',
        instructionSiEn: 'Dining setup සම්පූර්ණ වීමට: 1 Service Area + 1 Table + Table PINs (අවශ්‍ය නම්) + Active Branch QR එකක් ජනනය කර තිබිය යුතුය.',
      },
      {
        number: 2,
        title: 'Check Menu Stage',
        titleSiEn: 'Menu අදියර පරීක්ෂා කරන්න',
        instruction: 'Requires at least 1 Category AND at least 1 active menu item.',
        instructionSiEn: 'අවම වශයෙන් එක් Category එකක් සහ එක් Active Menu Item එකක් තිබිය යුතුය.',
      },
      {
        number: 3,
        title: 'Check Test Order Stage',
        titleSiEn: 'Test Order අදියර පරීක්ෂා කරන්න',
        instruction: 'A test order must reach CONFIRMED, PREPARING, or READY status. Orders that were cancelled or rejected do NOT count as success.',
        instructionSiEn: 'Test Order එක Confirmed, Preparing හෝ Ready තත්ත්වයට පත්විය යුතුය. Cancel වූ orders සාර්ථක ලෙස නොසැලකේ.',
      },
    ],
    relatedArticles: ['complete-business-setup', 'core-vs-recommended-setup'],
    directAction: {
      label: 'Open Business Setup',
      labelSiEn: 'Business Setup වෙත යන්න',
      href: '/dashboard/setup',
    },
  },
  {
    slug: 'slow-page-loading-troubleshooting',
    title: 'Troubleshooting: Realtime Connection & Page Performance',
    titleSiEn: 'ගැටළු විසඳීම: Realtime Connection සහ වේගය පිළිබඳ ගැටළු',
    description: 'Tips for running WSNexa smoothly on tablets, smartphones, and low-bandwidth restaurant Wi-Fi networks.',
    descriptionSiEn: 'අඩු වේගයක් සහිත Wi-Fi ජාල වලදී හෝ Tablet devices වල WSNexa වේගවත්ව ක්‍රියාත්මක කරගැනීම.',
    category: 'troubleshooting',
    keywords: ['slow loading', 'offline', 'realtime reconnect', 'network delay', 'performance'],
    troubleshooting: true,
    estimatedReadMinutes: 2,
    steps: [
      {
        number: 1,
        title: 'Check Restaurant Wi-Fi Stability',
        titleSiEn: 'Wi-Fi ජාලයේ ස්ථායිතාව පරීක්ෂා කරන්න',
        instruction: 'Ensure kitchen and cashier tablets have uninterrupted Wi-Fi access to maintain active realtime order subscriptions.',
        instructionSiEn: 'Kitchen සහ Cashier tablets සඳහා ස්ථාවර Wi-Fi සම්බන්ධතාවයක් ඇති බව තහවුරු කරගන්න.',
      },
      {
        number: 2,
        title: 'Use Modern Chromium Browser',
        titleSiEn: 'Google Chrome හෝ Safari භාවිතා කරන්න',
        instruction: 'For fastest rendering, use the latest version of Google Chrome, Safari, or Microsoft Edge.',
        instructionSiEn: 'උපරිම වේගය සඳහා Google Chrome හෝ Safari browser හි නවතම සංස්කරණය භාවිතා කරන්න.',
      },
    ],
    relatedArticles: ['what-is-wsnexa', 'kitchen-queue-kds-overview'],
    directAction: {
      label: 'Open Help Center',
      labelSiEn: 'Help Center වෙත යන්න',
      href: '/dashboard/help',
    },
  },
];
