import { HelpArticle } from '../types';

export const VENUE_PROFILE_DISCOVERY_ARTICLES: HelpArticle[] = [
  {
    slug: 'publishing-your-venue-profile',
    title: 'How to Publish and Manage Your Venue Profile',
    titleSiEn: 'Venue Profile එක සකස් කර Publish කරන්නේ කෙසේද?',
    description: 'Set your public storefront logo, banner image, cuisine categories, Google Maps location, and customer contact details.',
    descriptionSiEn: 'ඔබගේ restaurant එකෙහි Logo, Banner Photos, කෑම වර්ග සහ Google Maps location සකස් කරන ආකාරය.',
    category: 'venue-profile-discovery',
    keywords: ['venue profile', 'public storefront', 'photos', 'cuisines', 'discovery', 'google maps'],
    contextRoutes: ['/dashboard/venue-profile'],
    estimatedReadMinutes: 3,
    steps: [
      {
        number: 1,
        title: 'Open Venue Profile Settings',
        titleSiEn: 'Venue Profile වෙත යන්න',
        instruction: 'Navigate to Settings → Venue Profile (/dashboard/venue-profile) in the dashboard sidebar.',
        instructionSiEn: 'Dashboard sidebar එකෙන් Settings → Venue Profile (/dashboard/venue-profile) වෙත යන්න.',
      },
      {
        number: 2,
        title: 'Upload Media & Add Cuisines',
        titleSiEn: 'Photos upload කර Cuisines ඇතුළත් කරන්න',
        instruction: 'Upload a crisp venue logo and cover photo. Select cuisine tags (e.g. "Italian", "Seafood", "Bakery") and write a short bio.',
        instructionSiEn: 'Logo සහ Cover photo upload කරන්න. Cuisines (උදා. "Italian", "Seafood") තෝරා කෙටි හැඳින්වීමක් ලියන්න.',
      },
      {
        number: 3,
        title: 'Publish Storefront',
        titleSiEn: 'Storefront එක Publish කරන්න',
        instruction: 'Click "Save Profile". Your public venue page becomes accessible at /venues/[slug] for guests.',
        instructionSiEn: 'Save Profile click කරන්න. දැන් පාරිභෝගිකයින්ට /venues/[slug] ඔස්සේ ඔබගේ venue පිටුව නැරඹිය හැක.',
      },
    ],
    relatedArticles: ['managing-customer-reviews', 'table-reservations-basics'],
    directAction: {
      label: 'Open Venue Profile',
      labelSiEn: 'Venue Profile වෙත යන්න',
      href: '/dashboard/venue-profile',
    },
  },
  {
    slug: 'managing-customer-reviews',
    title: 'How to Monitor & Respond to Customer Reviews',
    titleSiEn: 'Customer Reviews සහ Ratings පරීක්ෂා කර ප්‍රතිචාර දැක්වීම',
    description: 'Read guest feedback, star ratings, and service impressions submitted after dining checkout.',
    descriptionSiEn: 'කෑම ගැනීමෙන් පසු පාරිභෝගිකයින් ලබාදෙන Star Ratings සහ Feedback පරීක්ෂා කිරීම.',
    category: 'venue-profile-discovery',
    keywords: ['reviews', 'ratings', 'customer feedback', 'guest satisfaction'],
    contextRoutes: ['/dashboard/reviews', '/dashboard/customers'],
    estimatedReadMinutes: 2,
    steps: [
      {
        number: 1,
        title: 'Open Reviews Dashboard',
        titleSiEn: 'Reviews Dashboard එක open කරන්න',
        instruction: 'Navigate to Customers → Reviews (/dashboard/reviews) from the dashboard sidebar.',
        instructionSiEn: 'Dashboard sidebar එකෙන් Customers → Reviews (/dashboard/reviews) වෙත යන්න.',
      },
      {
        number: 2,
        title: 'Analyze Ratings & Feedback',
        titleSiEn: 'Ratings සහ Feedback විශ්ලේෂණය කරන්න',
        instruction: 'Filter reviews by branch, date range, or star rating to spot customer service trends.',
        instructionSiEn: 'Branch, දිනය හෝ Star Rating අනුව filter කර පාරිභෝගික තෘප්තිමත්භාවය නිරීක්ෂණය කරන්න.',
      },
    ],
    relatedArticles: ['publishing-your-venue-profile'],
    directAction: {
      label: 'View Reviews',
      labelSiEn: 'Reviews බලන්න',
      href: '/dashboard/reviews',
    },
  },
  {
    slug: 'table-reservations-basics',
    title: 'Table Reservations & Guest Booking Inquiries',
    titleSiEn: 'Table Reservations සහ Booking ඉල්ලීම් කළමනාකරණය',
    description: 'Track incoming table reservation requests, confirm guest booking times, and assign reserved tables.',
    descriptionSiEn: 'මේස වෙන්කරවා ගැනීමේ (Reservations) ඉල්ලීම් තහවුරු කිරීම සහ මේස වෙන්කර තැබීම.',
    category: 'venue-profile-discovery',
    keywords: ['reservations', 'table bookings', 'guest booking', 'party size'],
    contextRoutes: ['/dashboard/reservations'],
    estimatedReadMinutes: 3,
    steps: [
      {
        number: 1,
        title: 'Open Reservations Hub',
        titleSiEn: 'Reservations Hub එක open කරන්න',
        instruction: 'Click Reservations in the sidebar (/dashboard/reservations).',
        instructionSiEn: 'Dashboard sidebar එකෙන් Reservations (/dashboard/reservations) click කරන්න.',
      },
      {
        number: 2,
        title: 'Review Booking Details',
        titleSiEn: 'Booking විස්තර පරීක්ෂා කරන්න',
        instruction: 'View guest name, arrival time, party size, and special requests. Click "Confirm Booking" to allocate a dining table.',
        instructionSiEn: 'පැමිණෙන වේලාව, පුද්ගලයින් ගණන පරීක්ෂා කර "Confirm Booking" click කර table එකක් assign කරන්න.',
      },
    ],
    relatedArticles: ['publishing-your-venue-profile', 'create-service-areas'],
    directAction: {
      label: 'Open Reservations',
      labelSiEn: 'Reservations වෙත යන්න',
      href: '/dashboard/reservations',
    },
  },
];
