import { HelpArticle } from '../types';

export const WAITER_OPERATIONS_ARTICLES: HelpArticle[] = [
  {
    slug: 'waiter-terminal-overview',
    title: 'Waiter Mobile Terminal Guide & Overview',
    titleSiEn: 'Waiter Mobile Terminal භාවිතය සහ හැඳින්වීම',
    description: 'Learn how waitstaff take table orders on mobile phones, monitor guest service calls, and coordinate with the kitchen.',
    descriptionSiEn: 'වේටර්වරුන් smartphone එකෙන් මේස අසලදී orders ගැනීම, guest calls බැලීම සහ kitchen එක සමඟ සම්බන්ධ වන ආකාරය.',
    category: 'waiter-operations',
    keywords: ['waiter', 'waitstaff', 'mobile pos', 'tableside ordering', 'waiter terminal'],
    popular: true,
    contextRoutes: ['/dashboard/waiter'],
    estimatedReadMinutes: 3,
    steps: [
      {
        number: 1,
        title: 'Open Waiter Terminal',
        titleSiEn: 'Waiter Terminal එක open කරන්න',
        instruction: 'Waitstaff log in and land directly on the Waiter Terminal at /dashboard/waiter.',
        instructionSiEn: 'Waiters ලොග් වූ සැනින් කෙලින්ම Waiter Terminal (/dashboard/waiter) වෙත යොමුවේ.',
      },
      {
        number: 2,
        title: 'Take Table Orders',
        titleSiEn: 'මේස සඳහා Orders ගැනීම',
        instruction: 'Tap "🍽️ Take New Order / Menu" to open the tableside menu and take orders on your mobile phone.',
        instructionSiEn: '"🍽️ Take New Order / Menu" tap කර smartphone එක මඟින් මේසය අසල සිටියදීම orders ලබාගන්න.',
      },
      {
        number: 3,
        title: 'Respond to Assistance Calls',
        titleSiEn: 'Assistance Calls වලට ප්‍රතිචාර දක්වන්න',
        instruction: 'Check "Active Assistance Calls" on /dashboard/waiter. Tap "Accept Request ⚡" to take charge of a request, assist the guest at the table, and tap "Mark Completed ✓" when finished.',
        instructionSiEn: '/dashboard/waiter හි "Active Assistance Calls" බලන්න. මේසයකින් එන ඉල්ලීමක් භාරගැනීමට "Accept Request ⚡" click කර, සේවය සැපයූ පසු "Mark Completed ✓" click කරන්න.',
      },
    ],
    notes: [
      'The Waiter workspace is 100% mobile touch-optimized for one-handed smartphone use.',
    ],
    notesSiEn: [
      'Waiter Terminal එක smartphone එකකින් තනි අතින් පහසුවෙන් භාවිතා කළ හැකි වන පරිදි නිර්මාණය කර ඇත.',
    ],
    relatedArticles: ['taking-table-orders-as-a-waiter', 'approving-guest-qr-orders', 'guest-assistance-calls'],
    directAction: {
      label: 'Open Waiter Terminal',
      labelSiEn: 'Waiter Terminal වෙත යන්න',
      href: '/dashboard/waiter',
    },
  },
  {
    slug: 'taking-table-orders-as-a-waiter',
    title: 'How to Take Orders at the Table on Waiter Mobile',
    titleSiEn: 'මේසය අසලදී Waiter Mobile මඟින් Order එකක් ගන්නේ කෙසේද?',
    description: 'Step-by-step instructions for selecting dishes, adding guest modifier customizations, and sending orders straight to the kitchen.',
    descriptionSiEn: 'පාරිභෝගිකයා අසල සිටියදීම කෑම වර්ග තෝරා, modifiers ඇතුළත් කර ක්ෂණිකව kitchen එකට order එක යැවීම.',
    category: 'waiter-operations',
    keywords: ['take table order', 'take order', 'tableside pos', 'waiter order', 'send to kitchen'],
    contextRoutes: ['/dashboard/waiter', '/dashboard/waiter/order'],
    estimatedReadMinutes: 3,
    steps: [
      {
        number: 1,
        title: 'Tap "🍽️ Take New Order / Menu"',
        titleSiEn: '"🍽️ Take New Order / Menu" tap කරන්න',
        instruction: 'From /dashboard/waiter, tap "🍽️ Take New Order / Menu" to open the mobile ordering terminal.',
        instructionSiEn: '/dashboard/waiter වෙතින් "🍽️ Take New Order / Menu" click කර mobile ordering terminal එක open කරන්න.',
      },
      {
        number: 2,
        title: 'Add Items & Select Modifiers',
        titleSiEn: 'කෑම තෝරා Modifiers ඇතුළත් කරන්න',
        instruction: 'Select items to add them to cart. Choose modifiers (e.g. "Medium Rare", "No Salt") and add special notes.',
        instructionSiEn: 'කෑම items tap කරන්න. Popup එකෙන් Modifiers (උදා. "Medium Rare", "No Salt") තෝරන්න.',
      },
      {
        number: 3,
        title: 'Select Table & Place Order',
        titleSiEn: 'Table එක තෝරා Order එක Submit කරන්න',
        instruction: 'Select the destination dining table and tap "Place Order". The order enters CONFIRMED status and routes straight to the Kitchen Queue.',
        instructionSiEn: 'අදාළ Dining Table එක තෝරා "Place Order" click කරන්න. Order එක CONFIRMED වී ක්ෂණිකව Kitchen Queue එකට යොමුවේ.',
      },
    ],
    relatedArticles: ['waiter-terminal-overview', 'kitchen-queue-kds-overview'],
    directAction: {
      label: 'Open Waiter Terminal',
      labelSiEn: 'Waiter Terminal වෙත යන්න',
      href: '/dashboard/waiter',
    },
  },
  {
    slug: 'approving-guest-qr-orders',
    title: 'How to Review and Approve Guest QR Orders',
    titleSiEn: 'Guest QR Orders review කර Approve කරන්නේ කෙසේද?',
    description: 'When Waiter Approval is enabled, verify guest items before they are cooked by the kitchen.',
    descriptionSiEn: 'Waiter Approval සක්‍රිය කර ඇති විට පාරිභෝගිකයා දැමූ order එක තහවුරු කර Kitchen එකට යවන ආකාරය.',
    category: 'waiter-operations',
    keywords: ['approve order', 'qr approval', 'review order', 'waiter verify'],
    contextRoutes: ['/dashboard/waiter'],
    estimatedReadMinutes: 2,
    steps: [
      {
        number: 1,
        title: 'Check Pending QR Order Approvals',
        titleSiEn: 'Pending QR Order Approvals කොටස බලන්න',
        instruction: 'On /dashboard/waiter, view the "Pending QR Order Approvals" section at the top of the queue.',
        instructionSiEn: '/dashboard/waiter හි ඉහළින්ම ඇති "Pending QR Order Approvals" කොටස බලන්න.',
      },
      {
        number: 2,
        title: 'Review Items and Approve',
        titleSiEn: 'Items පරීක්ෂා කර Approve කරන්න',
        instruction: 'Review table number, customer name, and order items. Tap "Approve Order" to confirm and send to kitchen (or "Reject" if invalid).',
        instructionSiEn: 'මේස අංකය, පාරිභෝගිකයාගේ නම සහ items පරීක්ෂා කර "Approve Order" click කරන්න (හෝ අවලංගු නම් "Reject").',
      },
    ],
    relatedArticles: ['waiter-approval-before-kitchen', 'waiter-terminal-overview'],
    directAction: {
      label: 'View Pending Approvals',
      labelSiEn: 'Pending Approvals බලන්න',
      href: '/dashboard/waiter',
    },
  },
];

